# Heartsteps Matrix Completion using Nearest Neighbor Strategies

In [4]:
import numpy as np
import pandas as pd

In [5]:
# read in Heartsteps dataset
df_hs = pd.read_csv("data_use.csv")
df_hs

,user.index,date,time,5min_datetime,steps,rolling_sum,rt,sugg.decision.5min,send.sedentary,availability
0,1,7/22/2015,9:05:00,NaN,0,0,1,NaN,0,1
1,1,7/22/2015,9:10:00,NaN,0,0,1,NaN,0,1
2,1,7/22/2015,9:15:00,NaN,0,0,1,NaN,0,1
3,1,7/22/2015,9:20:00,NaN,0,0,1,NaN,0,1
4,1,7/22/2015,9:25:00,NaN,0,0,1,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...
228235,37,1/26/2016,20:40:00,NaN,0,0,1,NaN,0,1
228236,37,1/26/2016,20:45:00,NaN,0,0,1,NaN,0,1
228237,37,1/26/2016,20:50:00,NaN,0,0,1,NaN,0,1
228238,37,1/26/2016,20:55:00,NaN,0,0,1,NaN,0,1
228239,37,1/26/2016,21:00:00,NaN,0,0,1,NaN,0,1

## Define `transform_dnn`

In [67]:
def transform_dnn(df, day_partitions = 4, day_measure = 144, units = 37):
    """
    Transfom df into shape suitable for DNN use case.

    Parameters
    ----------
    df : pandas DataFrame
         a matrix of size Z x 10 (with a set of properties to be defined)
         ...
    day_partitions : int
        The number of partitions to split an individual day into. The 
        default value is 4. Maximally, the value of day_partitions is 
        day_measure.
    day_measure : int
        The number of measurements per "day" in df. The default is 144,
        which aligns with the measurements per day in the HeartSteps dataset.
    units : int
        The number of units in df. Default is 37 (in line with the HeartSteps dataset)        
    Returns
    ----------
    tuple (M, A)
    where M is a units x (day_partitions * D) x (day_measure / day_partitions) np array 
    that contains the outcome vectors of interest and A is a np array shape units x (day_partitions * D)
    that indicates in which unit/time combination a treatment was observed.
    D is the maximum length of days observed among all unit trials.
    """
    # first, find the maximum trial length in days
    # units are 1-indexed
    max_days = 0
    num_days = []
    for i in range(1, units + 1):
        len_i = len(df[df['user.index'] == i]) // day_measure
        num_days.append(len_i)
        if len_i > max_days:
            max_days = len_i
    # init M and A
    M = np.zeros((units, day_partitions * max_days, day_measure // day_partitions))
    A = np.zeros((units, day_partitions * max_days))
    
    for i in range(units):
        # note: i is used to index into M and A.
        # unit_ind is used to retrieve unit specific values from df
        unit_ind = i + 1
        
        # slice by unit
        df_unit = df.loc[df["user.index"] == unit_ind]
        
        # pad first to max trial length to maintain partition size across units
        trial_steps = df_unit["steps"].to_numpy()
        trial_trt = df_unit["treatment"].to_numpy()
        if num_days[i] < max_days:
            # pad with 0s, step values are masked by trt
            pad = np.zeros((max_days - num_days[i]) * day_measure)
            trial_steps = np.append(trial_steps, pad)
            pad_trt = np.zeros((max_days - num_days[i]) * day_measure)
            trial_trt = np.append(trial_trt, pad_trt)
            
        # first split into days, then into partitions
        lst_days = np.split(trial_steps, max_days)
        parts = np.array([np.split(x, day_partitions) for x in lst_days])
         
        # Shape of parts is max_days x day_partitions x (day_measure // day_partitions)
        # Flatten along d dimension to achieve (day_partitions * max_days) x (day_measure // day_partitions) shape
        unit_parts = parts.reshape((max_days * day_partitions, day_measure // day_partitions))
        
        # Repeat for treatment col. 
        lst_days_trt = np.split(trial_trt, max_days)
        parts_trt = np.array([np.split(x, day_partitions) for x in lst_days_trt])
        unit_trt = parts_trt.reshape((max_days * day_partitions, day_measure // day_partitions))
        
        # if any of the trt values within the partition is 1, set the value in the final array to 1
        unit_trt_agg = unit_trt.any(axis = 1).astype(int)
        
        M[i] = unit_parts
        A[i] = unit_trt_agg
        A = A.astype('int32')
    return M, A

Question: could padding 0s to max trial length cause problems? i.e. people who have longer trials might be artificially more similar to each other compared to participants with shorter trial dates who now have no activity after the end of their trial date.

## Testing `transform_dnn` with simulated symmetrical data

We create a small test dataset as a proof of concept of the above data transformation. This data set will have 3 units over a time span of 4 days, with 12 measurements a day. We partition each day into 3 segments (4 measurements per partition). The treatment is randomly applied across each day and time span. This is a simpler example than the actual use case, as the number of days within the trial is consistent for all users. See the section below for a more complex example.

In [69]:
# create test set

# user inds
u1 = np.repeat(1, 12 * 4)
u2 = np.repeat(2, 12 * 4)
u3 = np.repeat(3, 12 * 4)
user_index = np.concatenate((u1, u2, u3))

# step measurements (for simplicity, between 1 and 10)
rng = np.random.default_rng()
u1_steps = rng.integers(low=1, high=10, size=12 * 4)
u2_steps = rng.integers(low=1, high=10, size=12 * 4)
u3_steps = rng.integers(low=0, high=10, size=12 * 4)
steps = np.concatenate((u1_steps, u2_steps, u3_steps))
 
# treatment measurements
# in practice, it seems much more likely to see no treatment rather than a treatment
u1_trt = np.random.choice([0, 1], 12 * 4, p=[0.8, 0.2])
u2_trt = np.random.choice([0, 1], 12 * 4, p=[0.8, 0.2])
u3_trt = np.random.choice([0, 1], 12 * 4, p=[0.8, 0.2])
trt = np.concatenate((u1_trt, u2_trt, u3_trt))

# create final dataframe
final_np = np.stack((user_index, steps, trt), axis = 1)
df_symtest = pd.DataFrame(final_np, columns = ["user.index", "steps", "treatment"])
df_symtest

     user.index  steps  treatment
0             1      8          0
1             1      7          0
2             1      6          0
3             1      3          1
4             1      5          0
..          ...    ...        ...
139           3      8          1
140           3      3          0
141           3      6          0
142           3      2          1
143           3      8          1

[144 rows x 3 columns]

Now that we have created our test set, we can use `transform_dnn` to demonstrate the desired transformation properties.

In [70]:
M, A = transform_dnn(df_symtest, day_partitions = 3, day_measure = 12, units = 3)

In [71]:
M

array([[[8., 7., 6., 3.],
        [5., 5., 5., 1.],
        [7., 9., 1., 2.],
        [9., 3., 1., 8.],
        [5., 3., 6., 1.],
        [9., 4., 8., 5.],
        [4., 6., 4., 9.],
        [4., 8., 6., 5.],
        [1., 8., 5., 3.],
        [1., 5., 4., 4.],
        [6., 3., 6., 9.],
        [8., 3., 7., 7.]],

       [[5., 6., 3., 8.],
        [8., 8., 6., 4.],
        [4., 2., 7., 9.],
        [3., 7., 3., 5.],
        [9., 9., 9., 3.],
        [4., 7., 3., 6.],
        [3., 3., 1., 1.],
        [4., 5., 6., 9.],
        [8., 1., 1., 4.],
        [6., 3., 2., 1.],
        [2., 4., 8., 1.],
        [2., 5., 6., 2.]],

       [[0., 7., 5., 9.],
        [2., 5., 9., 1.],
        [4., 7., 3., 5.],
        [9., 3., 7., 2.],
        [8., 1., 0., 6.],
        [7., 9., 5., 4.],
        [0., 7., 2., 7.],
        [2., 4., 0., 9.],
        [5., 5., 1., 8.],
        [6., 7., 3., 6.],
        [2., 3., 6., 8.],
        [3., 6., 2., 8.]]])

In [72]:
A

array([[1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1]])

## Testing `transform_dnn` on simulated asymmetrical data

Next, we test the function on a dataset with asymmetrical trial periods. As before, we will have 3 units, but this time, one of the units has a longer 6 day trial period. The remaining units have a 4 day trial period. There are still 12 measurements a day, and each day has 3 segments.

In [73]:
# create test set
# user inds, u1 has 6 day trial period
u1 = np.repeat(1, 12 * 6)
u2 = np.repeat(2, 12 * 4)
u3 = np.repeat(3, 12 * 4)
user_index = np.concatenate((u1, u2, u3))

# step measurements (for simplicity, between 1 and 10)
rng = np.random.default_rng()
u1_steps = rng.integers(low=1, high=10, size=12 * 6)
u2_steps = rng.integers(low=1, high=10, size=12 * 4)
u3_steps = rng.integers(low=0, high=10, size=12 * 4)
steps = np.concatenate((u1_steps, u2_steps, u3_steps))
 
# treatment measurements
# in practice, it seems much more likely to see no treatment rather than a treatment
u1_trt = np.random.choice([0, 1], 12 * 6, p=[0.8, 0.2])
u2_trt = np.random.choice([0, 1], 12 * 4, p=[0.8, 0.2])
u3_trt = np.random.choice([0, 1], 12 * 4, p=[0.8, 0.2])
trt = np.concatenate((u1_trt, u2_trt, u3_trt))

# create final dataframe
final_np = np.stack((user_index, steps, trt), axis = 1)
df_asymtest = pd.DataFrame(final_np, columns = ["user.index", "steps", "treatment"])
df_asymtest

     user.index  steps  treatment
0             1      6          0
1             1      1          0
2             1      7          0
3             1      6          1
4             1      9          1
..          ...    ...        ...
163           3      2          0
164           3      2          1
165           3      9          0
166           3      3          0
167           3      6          0

[168 rows x 3 columns]

In [74]:
M_a, A_a = transform_dnn(df_asymtest, day_partitions = 3, day_measure = 12, units = 3)

In [75]:
M_a

array([[[6., 1., 7., 6.],
        [9., 7., 6., 4.],
        [8., 6., 8., 5.],
        [3., 9., 8., 5.],
        [2., 3., 8., 8.],
        [8., 3., 2., 1.],
        [4., 1., 3., 3.],
        [8., 4., 5., 8.],
        [6., 5., 9., 6.],
        [6., 2., 2., 8.],
        [4., 8., 9., 9.],
        [9., 4., 7., 4.],
        [2., 4., 9., 3.],
        [5., 7., 9., 7.],
        [3., 2., 7., 3.],
        [1., 6., 8., 1.],
        [4., 2., 9., 1.],
        [6., 5., 1., 2.]],

       [[4., 2., 6., 2.],
        [8., 3., 1., 7.],
        [8., 9., 9., 5.],
        [2., 4., 2., 1.],
        [7., 1., 3., 8.],
        [4., 2., 5., 2.],
        [7., 4., 7., 5.],
        [1., 3., 9., 4.],
        [1., 8., 1., 5.],
        [8., 4., 8., 8.],
        [9., 2., 1., 6.],
        [3., 5., 2., 2.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[5., 3., 4., 2.],
        [2., 2., 4., 1.],
        [1., 9., 1., 4.],
        [7., 2., 8., 6.],
        [2., 3., 5., 5.],
        [2., 5., 0., 8.],
        [1., 9., 8., 2.],
        [0., 4., 6., 6.],
        [5., 5., 3., 2.],
        [5., 2., 2., 4.],
        [6., 0., 0., 2.],
        [2., 9., 3., 6.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [76]:
A_a

array([[1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

## Test `transform_dnn` on HeartSteps dataset

Finally, we test `transform_dnn` on its primary use case, the HeartSteps dataset. We use `send.sedentary` as the "treatment" indicator.

In [77]:
df_hs["treatment"] = df_hs["send.sedentary"]

We can see that there are 37 units. Time statistics run from 9:05 to 21:00 at 5 minute intervals, yielding 12 observations per hour for 12 hours. This means that there are 144 measurements per day. We will demonstrate by partitioning the data into 4 sections per day (i.e. each section has 36 measurements).

In [81]:
# note/question: it seems that 4 measurements may be too granular to find enough neighbors
M_hs, A_hs = transform_dnn(df_hs, day_partitions = 4, day_measure = 144, units = 37)

In [82]:
with np.printoptions(threshold=np.inf):
    print(M_hs[0, :, :])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  67. 115.  60.   0.  61.   0.
  169.   0.   0. 524. 324.   0.  26.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 212. 396. 457. 246.   0. 102.
    0.   0.   0.   0.   0.  38.   0.   0.  64. 102.   0. 123.  74. 221.
    0.   0. 260. 154.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  62.   0.  60. 170.  28. 326.  25.
    0.   0.   0.   0.   0.  92.  21.  57.   0.  25. 135.  22.   0.   0.
   72.  32.  70.  70. 108.  68.  25.   0.]
 [ 83.  31.  18.   0.   0.   0.  93.  33.  56. 135. 365. 580. 584. 584.
  576. 558. 523.  88. 229.   0.   0.   0.   0. 140.   0.   0.   0.  92.
   27. 227.   0.   0.   0. 156. 122.  89.]
 [590. 587. 279.   4. 113. 131.   0.   0.   0.   0.   0.   0. 136. 101.
   12.  89. 129.  60. 148.  81.  65.   0.  44.   0.  88. 196.  50.  54.
   89. 210.  52. 194. 143. 121. 294. 126.]
 [206. 147. 277. 350. 119. 147. 157.   0. 183. 349. 204.   0. 173. 202.
   44.  13.   0.   0. 150.   0.   0.   0.   0. 174.  20.  92.   0. 161.
  210. 176. 145.  38. 104.  79.  74. 149.]
 [180.  28.   0.   0.   0.  75. 258.  52.  40. 519. 491. 523. 486. 459.
  505. 528. 579. 445. 212. 258.  61.  83. 223. 340.  32. 508. 498. 407.
  491. 479. 448. 207. 129.   0.   0. 115.]
 [ 23. 200.  41.  12. 108.  14.   0.  25.   0.   0.   0.   0.  19.  24.
    0.   0.   0.   0.   0.   0.  24.  62. 211.  62. 146.   0. 114.  72.
    0.  52.  22.   0.   0.   0.   0.   0.]
 [595. 562. 575.  28.   0.  29.   0.   0.   0.   0.   0.  90.   0.   0.
    0.   0.   0.   0.  87.  25.   0.   0.   0.   0. 205.  39. 135.  18.
   25. 143.  19.  35.  54.  21.  14.  41.]
 [136. 106.  27. 132.  47.  22.  21.  50.  37. 159.  12.   0. 240.  92.
   38.  54. 187. 229. 151.  92.   0.  18. 149.  79. 123.   0.  27.   0.
   36.  20. 110. 123.  43.  67.  56.  16.]
 [  0.  66. 110.   0.  97.  19.  51.  53. 247. 139.  15. 182. 443. 274.
  527. 561. 559. 438. 542. 495. 489. 134.  41.  35.   0.   0.   0. 189.
  325. 416. 553. 583.  98.  76.   0.   0.]
 [  0.   0.   0.  47.  47.   0.   0.   0.  46.  17. 361. 356. 565. 432.
  277.  27.  25.   0.   0.   0.  66.  70. 116. 195.  36.  71.  18.   0.
   18.  73. 289.  66. 104. 225. 422. 487.]
 [ 28.  28.  81.  19.   0.   0.   0.   0.   0. 205.  40. 170.  64.   0.
   26.  48. 147. 142.  23.   0.  25.  48.   0.   0.  18.   0.   0.   0.
    0.  63.   0.   0.   0.   0.  36.   0.]
 [  0.   0.  55.   0.   0.   0.  82.   0.   0.   0.   0.   0.   0.  40.
    0.  49.  87.  99.  74.  42.   0.   0.   0.   0.   0.   0.  74. 151.
  520. 525. 203.  52.  80. 104. 104.  42.]
 [368. 475. 345.  47.   0.   0.  34.   0.   0.   0.  98.  82. 100. 284.
  156.   0. 159.   0.   0. 249.   0.   0.  25.   0.   0.   0.   0.   0.
   84. 190. 176. 128. 187.   0.   0.  12.]
 [ 53.  22.  49. 241.  86.   0.  60.  84.  45.  22.   0.   0.   0.   0.
    0. 182. 123.  48.  84.   0.  18.   0.  27.   0.   0.   0.  96.   0.
    0.   0.  19. 358.   0.   0.  16.  24.]
 [  0.   0.   0.   0.   0.  56.  25. 116. 284.  35.   0.   0.  27.  20.
   27.  44.  41. 217. 102. 371. 277. 264. 436. 415. 300. 228. 206. 292.
  118. 268.  60.  41.   0. 144.   0.   0.]
 [111. 136. 337. 251. 386. 263. 398. 275. 277. 197.   0.   0.  35. 224.
   54. 166. 391. 291.   0.  93. 310. 340. 253. 419. 169. 205. 279. 117.
  121.  17.  54.  41.  59. 243. 279. 454.]
 [454. 320. 197. 334. 371. 370. 166.   0.  57.  96.  22.   0.  59.  87.
  176. 116.  38.  60.  21.  25.  54.  85.   0. 151. 190. 435.  14.  51.
  157. 189.  82. 122.   0.   0.   0.   0.]
 [ 20.  95.  72.  87.  19.   0.  53.  74.   0.   0.  27.  28.  39.  97.
   23.  22.  44.   0.   0.   0.   0. 113.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 66.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  208.   0.   0.   0. 104.   0.   0.   0.   0.   0.   0.  50.   0.   0.
    0.   0.   0.  26.  59.   0.   0.   0.]
 [  0.   0.   0.  24.   0.   0.   0.   0.   0.   0.   0.   0.   0. 213.
   45.   0.   0.   0.   0.  63.  64.  56.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 526. 557. 584. 573.]
 [468. 105.  17.   0.   0.   0.  55. 173.   0.   0.   0.   0. 107. 392.
  372. 197.   0.   0.   0.   0. 141. 163.  94.  67.   0.   0.   0.   0.
    0.  81. 126.  44.   0.  58. 170. 134.]
 [  0.  73.   0.   0.   0.   0.  25. 304. 303. 422. 523. 521. 531. 513.
  515. 340. 320. 310. 598. 597. 588. 596. 563. 173.   0.   0.   0.   0.
    0. 102.  20.   0.   0.  30.   0.   0.]
 [ 54.   0.   0.   0. 158.   0.   0.   0. 197.   0.   0.   0. 217.  97.
    0.   0.   0.   0.  55.  71.  73.   0.  94.   0.  19.   0.   0.   0.
    0.   0.   0.  19.  53. 391. 230. 368.]
 [ 20.  46.   0.   0.   0.   0.   0.   0.  40. 224.   0.  20.  55.  23.
  252. 290.   0.   0.   0.  70. 121.  10.  61.   0.   0.   0.   0.   0.
    0.   0. 230. 390. 575. 586. 575. 562.]
 [114.   0.  55.  16.   0.   0.   0.   0.   0.   0. 189. 386.   0.   0.
    0.   0.   0.  43.  91.  47.   0.  25.  74. 133.  20.  44.   0.  35.
   30. 120.  55.   0.  18.  30.  21.  83.]
 [ 15.  24.  36. 198. 321. 427. 491. 446. 347. 432. 404. 444. 372. 410.
  478. 445. 366. 437. 497. 451. 501. 229. 261. 451. 417. 267. 471. 395.
  427. 185. 332. 597. 595. 598. 578. 548.]
 [334.  34.   0.   0.   0.  33.   0.  50.   0.   0.  72.  66.   0.   0.
    0.   0.   0.  22.   0.   0.   0.   0.   0.   0. 235. 231.  29.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  18.  37.  78. 588. 587. 591. 591. 332.
    0.   0.  72.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 248.  28.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 168.   0.   0.   0.   0.   0.   0.   0.   0.   0. 187.
    0.   0. 278.   0.   0.   0.   0.  29.  52.  48. 158.   0.   0.  41.
   46.  20.  62.   0.   0.  84.   0.   0.]
 [  0.  55. 153. 204. 216. 134. 201. 193. 200. 183.  35.  33. 230. 203.
   98. 218. 257. 223. 289. 261. 142.  26.   0.  19.   0.   0. 278. 226.
  222. 170.   0.  35. 204. 166. 244. 205.]
 [  0.   0.   0.   0.   0.   0.   0.  52.   0.   0.   0.   0.   0.   0.
    0.   0.  14.   0.   0.   0. 120.   0.   0.   0.  23. 278.   0.   0.
    0.   0.   0.   0.  84. 112.   0.   0.]
 [  0.   0.   0.   0.   0. 273.  51.   0.   0.   0.   0.   0.   0.   0.
    0.  90.   0.   0.   0.   0.   0.  37.   0.  44. 321. 576. 583. 576.
  571. 146.  80.  96.   0.   0.   0.   0.]
 [  0.  28. 228.   0.   0.   0.   0.   0.   0. 135.   0.   0. 178.  53.
   31. 106. 260.   0.   0.   0.   0.   0. 125. 227.  62.  72. 177. 555.
  447.  42.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  56.   0.   0.   0.   0.  53.   0.
   37.  44.  25.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   55.  70.   0.   0.  37.  18.  82. 287.]
 [  0.   0.  94.  51.   0.  36.  77.   0.  36.  46.   0.   0. 222. 257.
  112.   0.   0.   0.   0. 261. 245. 438. 351. 200. 357. 261.   0.   0.
  160.   0. 104. 272. 128.   0.  23. 175.]
 [  0. 100. 351.   0.   0.   0.   0. 105. 146.   0.   0.   0. 213. 392.
    0.   0.   0.   0. 215.  68.  17.   0.   0.  87. 508. 285. 135.  81.
  197. 358. 183. 197. 264. 189. 249. 243.]
 [ 73.   0. 106. 207. 287. 553. 514. 510. 401. 320. 400. 391. 395. 289.
  339. 388. 383. 428. 361. 289. 374. 311. 359. 219. 490. 390. 421. 277.
  370. 378. 403. 291. 349. 189. 296. 287.]
 [278.  30.   0. 316. 332. 366. 240. 325. 210. 356. 417. 408. 216. 174.
   34.  49. 478. 559. 505. 538. 552. 541. 556. 374. 156. 507. 541.  17.
   27.   0.   0. 162.  86. 204.  99. 128.]
 [394. 241. 413. 389. 336. 340. 345. 343. 365. 275. 306. 213. 334. 221.
  333. 313. 316. 478. 379. 282. 327. 311. 344. 263.  46.   0.   0.  73.
   19.   0.   0.   0.  41.  52. 243.  44.]
 [247. 100.  96. 107.  45.   0.  39.   0.   0.  53.  91.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 166. 261.   0.   0. 149.   0.  70.  41.
   48. 146. 122.  90. 154. 135. 145.   0.]
 [133.  67.  96. 182. 109.  22. 137.  76. 112.  46.  63.   0. 139.  25.
   38. 128.   0. 133.  75.  84.  93.   0.  83.  60.  59. 160.  90.  75.
   56.  50.  52.  70.  59.  52. 176. 123.]
 [ 49.  84.  81. 161. 156. 141. 308.   0.   0.  41.  18.   0.   0.   0.
    0.   0.  20.   0.   0.   0.   0.   0. 238.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 112.  75.   0.]
 [  6.  86.  46.  55.  33.   0.  48.   0.   0.  56. 217.   0. 121. 155.
  303. 330. 253. 140. 123. 277. 214. 198. 204. 286. 286. 266. 147.   0.
   23. 145. 204. 300. 337. 307. 305. 398.]
 [320. 158.   0.   0.  88. 292. 351. 302.  75. 145. 163. 330. 297.   0.
   28.  77.  23. 229. 148.  42.   0.   0.  18. 160. 180. 141.  50.  36.
   24.   0. 107.   8.   0.  18. 116.   0.]
 [ 52.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  35.
    0.  92.  86. 331. 275. 186. 346. 251. 123.  21.  47.  47. 128. 171.
  297.  69.  18.   0. 113.  96.  23. 108.]
 [ 66.   0.   0.   0. 117. 111. 174. 425.  42.   0. 112. 110.  46.  45.
  126.   0.   0.  88.   0. 188.  65.  26.   0.   0.   0. 208. 299.  45.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  46.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  64.  77.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  19.  48.   0.   0.]
 [  0.   0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  37.   0.   0.   0.  30.   0.   0.   0.   0.   0.   0.   0.  46.
  138. 110.   0.   0.   0.   0.   0.   0.]
 [  0.  79. 406. 331. 378. 399.  42. 131. 308.  83.  88. 212.   0.  40.
    0. 288.  47.   0.   0.   0.   0.   0.  96. 119.  35. 140. 179. 257.
  182. 181.  80.  89. 417. 259.   0.   0.]
 [ 55.   0.   0.  26.  94. 172. 210. 358. 363. 293.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0. 353. 504. 340. 268.   0.  74.
  273.   0.   0.   0.  97. 196. 155.   0.]
 [  0.   0.   0.   0.  44. 257.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  93. 335.   0.   0.   0.  19.   0.]
 [  0.   0.   0.  84. 132.   0.  25. 253.  25.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 293. 433. 103.   0.   0.   0.   0.   0.   0.   0.
   15.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 220.   0. 229. 238. 248.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 326.  18.   0.   0.   0.   0.   0.  53.
  186. 107.  87. 112.  93.   0.  55.  43.]
 [ 25.  50.   0.   0.   0.  77. 140.   0.   0.  97.  25.   0.   0.   0.
    0. 253. 217.  21.  69.   0.   0.   0.   0.   0.  27.   0.   0.   0.
    0.   0.  54.   0.   0.  31. 342.  60.]
 [ 76.  44.   0.  68. 294. 185.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  16.  18.   0.   0.   0.   0.   0.   0.   0.  48.   0.
    0.   0.   0.   0.   0.  37.  56. 169.]
 [209. 182.   0.   0. 139. 156.   0. 149. 163.   0.  18.   0.   0.   0.
  234.  70.   0.   0.   0.  73. 449. 577. 591. 585. 481. 152.  72.   0.
    0.   0.   0.   0.   0. 100. 439.  26.]
 [  0.   0.   0. 105. 109.   0.  67.   0. 104. 188. 369.  30.   0.   0.
    0.   0. 127.  81.  89.  96.  32.  26.  21.  25.  37.   0.   0.   0.
    0.  23.   0.  18.   0.   0.   0.   0.]
 [ 90.  79.  61.   0.   0.   0. 138.  48. 127. 179. 125.   0.  38.  12.
  109. 295. 126.  39. 293. 320. 266. 158.   0. 494. 166.  73.  42.  81.
  103. 160.  95. 134. 103. 114.  67. 176.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  221.   0.  68.   0.   0.   0.   0.   0. 175.  56.   0.   0.   0.  30.
    0.   0.   0.   0.  21.   0.   0.   0.]
 [  0.   0.   0.   0.  96.  41.  68.  18.   0.   0.  49.   0.  20.  69.
    0. 268.  90.   0.   0. 130. 581. 580. 577. 577. 329.  67.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  65.   0.   0.   0.   0.  62.   0.  93. 291.   0.  34. 307.
   29.   0.   0.   0. 314.  93.   0.   0.  87. 262.  34.   0. 248.  21.
   36.  57.   0.   0.  15.   0.  25.   0.]
 [  0.   0.  20.   0.  31. 339. 153.  25.   0.   0.  20. 517.   0.   0.
   46. 319.   0.   0.  46.  30. 227.  89.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  75.   0.   0.   0.]
 [  0.   0.   0.   0. 316. 105.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 127. 183.   0.   0.   0.   0. 118. 280.   0.
    0.   0.  42.  35.  82. 179.   0. 205.]
 [450. 237.  61.   0.   0.   0.  64. 225. 181.   0.   0.   0. 115.   0.
   60.  61.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  127. 373. 128. 127.   0.   0.   0.   0.]
 [  0.   0.   0. 390.  17.   0.   0.  63. 148.  16.   0.   0.  74.   0.
   31. 105.  74.   0.  27.   0.  33.  29.  27.   0.   0.   0.   0.   0.
   98.   0.   0.   0.  50.  16.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  43.  24.   0.   0.   0.   0.  69.   0.
    0.   0.   0.  23.   0.  18.  97. 102.  16. 101.  75. 213.   0.   0.
    0. 383.   0.   0. 103. 142.   0.   0.]
 [  0.   0. 159.   0. 131.   0.   0.  37.  39. 203. 307. 149.  78.  99.
  219. 299. 287. 166. 251. 143.   0. 197.  88. 175. 233. 225. 244. 162.
  393. 121. 310. 303. 321. 250. 250.   0.]
 [249. 306. 281. 125.  90.   0. 107.  12.  50. 344. 259. 154. 141. 353.
  145. 169. 260. 226.  41.  37. 320. 249. 338. 173. 125. 237. 343. 336.
   26. 122. 298.   0. 111.   0.  96. 195.]
 [335.  30.  35. 224. 328.   0.  61. 124.   0.  38.   0. 148. 133.   0.
  348. 335. 151. 156. 143. 231. 252.  91. 174.  66.   0.   0.  20. 223.
  182. 309.  98. 222.  64.  16.  29. 120.]
 [215. 345. 395.  86. 292.  81. 118. 213. 247.  18.   0.  24. 191. 285.
    0.  12.   0.   0.   0.  25.   0.  52. 172. 173.  78.  25.  19.  29.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  30.   0.   0.   0. 162.
  132.  29.   0. 215.  75.  25.  55.  96.  89.   0.   0. 112. 154.  33.
   34.  98. 114.  27.   0. 194.   0.   0.]
 [  0.   0.  29.   0.   0.   0.   0.   0.   0. 159. 197.   0.   0.   0.
  357. 255. 195.  75.  18.  46. 126. 193.  48.   0.   0. 179. 117.  61.
   12.   0.   0.  46.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  73. 121.  54.  97. 217. 200. 169. 151. 151. 421.
  143.  67. 265. 265. 171. 113. 290. 149.  33. 165.  54.   0. 158.   0.
   36.  25.  36. 124. 260. 336. 202.  39.]
 [133. 183. 179. 235.   0. 230. 148. 106. 154. 220. 101.  52.   0.   0.
   18. 105.   0.  95.  43.  85.   0.  75. 109. 141. 156.   0.   0.   0.
   64.   0.  31.  25.  27.  24.   0.  80.]
 [  0.   0.   0.   0.   0.  48.   0.   0.   0.   0.   0.   0. 152. 183.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  54.   0.
    0.   0.   0.   0.   0.  23.   0.   0.]
 [  0.   0. 239.  80. 382.   9. 182. 186.  36.  43. 157.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 184.]
 [161.   0.   0.   0.   0.  98.   0.   0.  33. 117. 284.   0.   0.   0.
    0. 205. 125.   0.   0.   0.   0.   0.   0.  41.  84. 225.  56.  36.
    0.   0.  72.  25.   0.   0.   0.  88.]
 [262. 119. 175.   0. 224.   0.   0.   0.   0.   0.   0.  20. 249. 275.
  242. 187. 210. 216.   0.  82. 182. 211. 158.   0.  62.   0. 112.   9.
    0.   0.   0.   0.   0.  31.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 203.   0.   0.   0.  30.  79.  48.  23.
    0.  32. 135. 261.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  38.  41. 215.   0.  76.   0.]
 [  0.   0.  39.   0. 167.   0. 121. 384.  73.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  94.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 244.  94.   0.   0.   0.   0. 169. 425.   0.  45.   0.
  233. 142.   0.   0.   0.   0.  49.  19.  31.   0. 268. 150.  21.   0.
    0.  50. 132.   0.   0.   0.   0.  91.]
 [  0.   0.   0.   0.   0.  70.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  43.  76.   0.   0.   0. 144.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 23.   0.   0.   0. 256.  84. 124.   0.   0.   0.   0. 200.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  28.   0. 271.   0.   0.   0.   0.
    0.   0.   0.  86. 239. 325.  22. 126.]
 [  0.   0.   0.   0.   0.   0.  52.   0.   0. 140. 206.   0.  76.  73.
    0.  50.   0.   0.  40. 174.  39. 547. 576. 573. 563. 388.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  60.   0.   0.  84.  49.   0.   0. 194.  74.   0.  51.   0.
    0.   0.   0.   0.   0.  47.   0.  46.]
 [ 41.  25.  75.  24.   0.   0. 223. 120.   0. 144.  55.  41.   0.  42.
   73.   0.   0.   0.   0.   0.   0.   0.   0. 103.   0.  53.  25.  22.
    0.   0.  56.   0.  14.   0. 122.   0.]
 [  0.   0.   0.   0.   0.   0.  23. 138.  19. 132.  87. 124.   0.   0.
   20.  26.   0.   0.  99.   0.   0.   0. 140.   7.  33.   0.   0.  33.
   71.   0.  67.   0.   0. 177.   0.   0.]
 [  0.  57.   0.   0.   0.   0.   0.  40.   0.   0.  52.  31.  58.   0.
    0.  18.  54.   0.  48.  16.  77.   0.  30.   0.  38. 107.   0.   0.
    0.  66.  74. 160.  66.  32.  40.  33.]
 [  0. 250.  27.   0.   0.   0. 184.   0.   0.   0.   0.   0.   0.   0.
    0. 202.   0.  59.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  66. 124.  17.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  25.
  238. 214.   0.  22.   0.   0.   0.   0.   0.   0. 256. 273.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  16.]
 [  0.  79. 271.   3.   0.   0.   0.   0.   0.   0.   0.   0.   0.  95.
    0.   0.   0.   0.  21. 254.   0.  22.   0.   0.   0. 287.   0.   0.
    0.  52. 150. 140.  17.   0.   0.   0.]
 [  0. 131.  29.   0.   0.  94.  45.  95.  86.   0.  76.   4.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  57. 123.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  57.   0.   0. 159. 204.   0.   0.   0.  44.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  87. 109.   0. 164. 272.
  298.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  45.   0.   0.   0.   0.   0.   0.  23. 234. 307.   0.  88.   0.
    0. 165.  50.  75.  42.  69.  40.  25.   0.   0.   0.   0. 290.   0.
    0.  80. 111.  33.   0.   0.  25. 103.]
 [ 52.   0.   0.   0.   0.  41.  60.   0.   0.  39.  49.  18.   0.   0.
  145.   0. 313.   0.   0.   0.   0.   0.  66. 119.  19.   0.   0.  24.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 100. 261.  96.  18.   0.   0.   0.   0.  75.   0.  99.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  39.  30.   0.   0.  98.  77.   0.   0.
    0.   0.   0.  40.  25.   0.   0.  74.   0.   0.   0.   0.  35.   0.
    0.  77.   0.  91.   0. 273. 151.   0.]
 [  0.  51.   0. 178.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  30. 189.   0.   0.   0.  19.  59.  24.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  43.]
 [ 32.   0.   0.  38. 240. 518. 332.   0.  75.  73.  73.  14.   0. 144.
  115.   0.   0.   0.   0.  58.  50.  68.  19.  20.   0.   0. 125.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  94. 182.  28.  13.   0. 217. 293.  75.  52. 109.  82.   0.   0.
   63.   0.  20.   0.   0.   0.  68.   0.   0.  40.   0.   0.  91.   0.
    0.   0.   0.   0.  28.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 132. 239. 107.
    0.   0.  26.   0.   0.   0.   0.   0.  49.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  22.  48.]
 [262.  48.   0.   0.   0.   0.   0.  64.  21.   0. 111. 201.   0.  19.
   10.  20.  69.  22. 387. 281.   0.   0.   0. 152.  72.  37.  18.   0.
    0.  22.  37.  15.  76. 118.   0.  20.]
 [  0.   0.   0. 367.   0.   0. 135.   0.   0.   0.  40.  19.   0.   0.
  247.   0.   0.   0.   0.   0. 110.  19.  64.  18.  30.  52.   0.  37.

In [83]:
A_hs

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Li 2019 Nearest Neighbors Implementation

We implement the user-user nearest neighbors algorithm as defined in Nearest Neighbors for Matrix Estimation Interpreted as Blind Regression for Latent Variable Model (Li et al. 2019). More specifically, we construct Algorithm 2, which can be found in Section III [here](https://arxiv.org/abs/1705.04867).

First, to align the NN implementation with the data format considered above, we define a function to collapse the partitioned measurements dimension (3rd dim) to its mean.

In [91]:
def mean_collapse(A, d = 2):
    """
    Returns A (3d array) with dth dimension collapsed as mean
    """
    return np.mean(A, axis = d)

Next, we construct the necessary functions as defined in Li 2019.

In [90]:
def dissim_row(O, M, u, v):
    """
    Returns the row dissimilarity between rows u and v
    in O
    
    Parameters
    ----------
    O : a matrix of size a x b
    M : a masking matrix of size a x b that
        dictates which entries of O are known 
    u : the index of a row in O
    v : the index of a row in O

    Returns
    ----------
    d_row : the row dissimilarity between u and v (float)
    """
    obv_col_mask = M[u] * M[v]
    overlap = np.sum(obv_col_mask)
    if not overlap:
        return float('inf')    
    sd = (O[u] - O[v])**2 * obv_col_mask 
    msd = (1 / overlap) * np.sum(sd)
    return msd

def nearest_neighbors(O_1, u, M, eta):
    """
    Returns the B neighborbood around u using rows in O_1 within
    radius eta. 
    
    Parameters
    ----------
    O_1 : a matrix of size c x d
    M : a masking matrix of size c x d that
        dictates which entries of O_1 are known 
    eta : radius of B neighborhood
    
    Returns
    ----------
    B : neighborhood (indicies of most similar rows)
        with radius eta
    """
    dissims = np.array([dissim_row(O_1, M, u, v) for v in range(len(O_1))])
    # remove u from neighbors
    #dissims = np.delete(dissims, u, 1)
    B = np.nonzero(dissims <= eta)
    return B
    
    
    
def estimate_li_nn(Z, M, eta):
    """
    Returns A_hat, the estimate of partially unobvserved
    matrix A using Nearest Neighbors imputation
    
    Parameters
    ----------
    Z : an array of size m x n x q
    M : a masking matrix of size m x n that
        dictates which entries of Z are known 
    eta : radius of B neighborhood
    
    Returns
    ----------
    A_hat : the estimate of partially unobvserved matrix A
    """
    Z = mean_collapse(Z, d = 2)
    m, n = Z.shape
    A_hat = np.zeros((m, n))
    for u in range(m):
        for v in range(n):
            O_1  = np.delete(Z, v, axis = 1)
            O_2 = Z[:, v]
            M_v = np.delete(M, v, axis = 1)
            u_neighbors = nearest_neighbors(O_1, u, M_v, eta)
            # only select obvserved neighbors
            mask = M[u_neighbors, v]
            pos_nn = Z[u_neighbors, v]
            masked_nn = pos_nn[mask == 1]
            if not len(masked_nn):
                A_hat[u, v] = 0
            else:
                A_hat[u, v] = np.mean(masked_nn)
    return A_hat

def estimate_li_nn_inds(Z, M, eta, v_inds):
    """
    Returns A_hat, the estimate of partially unobvserved
    matrix A using Nearest Neighbors imputation, with only indices specified
    by v_inds estimated
    
    Parameters
    ----------
    Z : an array of size m x n x q
    M : a masking matrix of size m x n that
        dictates which entries of Z are known 
    eta : radius of B neighborhood
    v_inds : indices to estimate, tuple of (x_coords, y_coords)
    
    Returns
    ----------
    A_hat : the estimate of values in partially unobserved matrix A specified by v_inds
    """
    row_coords, col_coords = v_inds
    Z = mean_collapse(Z, d = 2)
    m, n = Z.shape
    A_hat = np.zeros((m, n))
    for i in range(len(row_coords)):
        u = row_coords[i]
        j = col_coords[i]
        O_1  = np.delete(Z, j, axis = 1)
        O_2 = Z[:, j]
        M_j = np.delete(M, j, axis = 1)
        u_neighbors = nearest_neighbors(O_1, u, M_j, eta)
        mask = M[u_neighbors, j]
        pos_nn = Z[u_neighbors, j]
        masked_nn = pos_nn[mask == 1]
        if not len(masked_nn):
            A_hat[u, j] = 0
        else:
            A_hat[u, j] = np.mean(masked_nn)
    return A_hat
        
# using the indexing strategy i am currently using, A_hat and A are both 1 dimensional. This might change.
def mse(A_hat, A):
    """
    Returns the mean squared error of estimate A_hat from ground truth A
    """
    return np.mean((A_hat - A)**2)

### Checking Li 2019 implementation correctness with worked example

In order to look for bugs in our cross validation and Li 2019 implementations, we create a sample dataset with some nice properties and compute the similarities by hand. This doesn't guarantee correctness, but it will catch simple errors/mistakes in understanding.

To start, we create a simulated datasest with 6 users over a two day trial period. There are 6 measurements per day and each day is broken into 3 segments. 3 of the users (A, B, and C) are similar to each other (roughly more steps in the evening/last measurement periods in the day) and the other 3 users (D, E, F) are different from the first 3 and similar to each other (roughly more steps in the morning/early measurement periods.  

Let's suppose the matrix is fully observed. To simulate a validation set, we mask out one segement for each user - these are the values we will try to impute.

In [28]:
# user inds
uA = np.repeat(1, 6 * 2)
uB = np.repeat(2, 6 * 2)
uC = np.repeat(3, 6 * 2)

uD = np.repeat(4, 6 * 2)
uE = np.repeat(5, 6 * 2)
uF = np.repeat(6, 6 * 2)

user_index = np.concatenate((uA, uB, uC, uD, uE, uF))

# step measurements
steps_uA = [1, 1, 2, 3, 5, 9, 1, 1, 3, 4, 5, 10]
steps_uB = [0, 2, 2, 4, 5, 11, 0, 2, 3, 3, 4, 12]
steps_uC = [0, 0, 2, 5, 7, 10, 2, 2, 1, 5, 6, 9]

steps_uD = [10, 5, 4, 3, 1, 1, 9, 5, 3, 2, 1, 1]
steps_uE = [12, 4, 3, 3, 2, 0, 11, 5, 4, 2, 2, 0]
steps_uF = [9, 6, 5, 1, 2, 2, 10, 7, 5, 2, 0, 0]
steps = np.concatenate((steps_uA, steps_uB, steps_uC, steps_uD, steps_uE, steps_uF))

# treatment indicators
trt_uA = [1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0]
trt_uB = [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0]
trt_uC = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

trt_uD = [1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0]
trt_uE = [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0]
trt_uF = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

trt = np.concatenate((trt_uA, trt_uB, trt_uC, trt_uD, trt_uE, trt_uF))
final_np = np.stack((user_index, steps, trt), axis = 1)
df_nn_test = pd.DataFrame(final_np, columns = ["user.index", "steps", "treatment"])
df_nn_test

    user.index  steps  treatment
0            1      1          1
1            1      1          0
2            1      2          1
3            1      3          0
4            1      5          0
..         ...    ...        ...
67           6      7          1
68           6      5          1
69           6      2          1
70           6      0          0
71           6      0          0

[72 rows x 3 columns]

In [51]:
data_full, mask = transform_dnn(df_nn_test, day_partitions = 3, day_measure = 6, units = 6)

In [52]:
data_full

array([[[ 1.,  1.],
        [ 2.,  3.],
        [ 5.,  9.],
        [ 1.,  1.],
        [ 3.,  4.],
        [ 5., 10.]],

       [[ 0.,  2.],
        [ 2.,  4.],
        [ 5., 11.],
        [ 0.,  2.],
        [ 3.,  3.],
        [ 4., 12.]],

       [[ 0.,  0.],
        [ 2.,  5.],
        [ 7., 10.],
        [ 2.,  2.],
        [ 1.,  5.],
        [ 6.,  9.]],

       [[10.,  5.],
        [ 4.,  3.],
        [ 1.,  1.],
        [ 9.,  5.],
        [ 3.,  2.],
        [ 1.,  1.]],

       [[12.,  4.],
        [ 3.,  3.],
        [ 2.,  0.],
        [11.,  5.],
        [ 4.,  2.],
        [ 2.,  0.]],

       [[ 9.,  6.],
        [ 5.,  1.],
        [ 2.,  2.],
        [10.,  7.],
        [ 5.,  2.],
        [ 0.,  0.]]])

In [53]:
mask

array([[1., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0.]])

First, we take the mean of the partitioned dimension to achieve the 2D structure.

In [54]:
data = mean_collapse(data_full)
data

array([[1. , 2.5, 7. , 1. , 3.5, 7.5],
       [1. , 3. , 8. , 1. , 3. , 8. ],
       [0. , 3.5, 8.5, 2. , 3. , 7.5],
       [7.5, 3.5, 1. , 7. , 2.5, 1. ],
       [8. , 3. , 1. , 8. , 3. , 1. ],
       [7.5, 3. , 2. , 8.5, 3.5, 0. ]])

Next, let's calculate the dissimilarities between each row. This is the mean squared difference between overlapping observed values. 

Dissim A-B: $\frac{((3 - 2.5)^2 + (1 - 1)^2 + (3.5 - 3.0)^2 + (7.5 - 8)^2)}{4} = \frac{0.75}{4} = 0.1874$

Dissim A-C: $\frac{(1-0)^2 + (3.5 - 2.5)^2 + (1)^2 + (0.5)^2 + 0^2}{4} = \frac{3.25}{4} = 0.8125$

Dissim A-D: $\frac{6.5^2 + 1^2 + 6^2 + 1^2 + 6.5^2}{5} = \frac{122.5}{5} = 24.5$

Dissim A-E: $\frac{0.5^2 + 6^2 + 7^2 + 6.5^2}{4} = 31.875$

Dissim A-F: $\frac{6.5^ + 0.5^2 + 7.5^2 + 0}{4} = 24.6875$ 

Dissim B-C: $\frac{0.5^2 + 0.5^2 + 1^2 + 0^2}{4} = 0.375$

Dissim B-D: $\frac{0.5^2 + 6^2 + 0.5^2 + 7^2}{4} = 21.375$

Dissim B-E: $\frac{0^2 + 7^2 + 7^2 + 0^2 + 7^2}{5} = 29.4$

Dissim B-F: $\frac{0^2 + 6^2 + 7.5^2 + 0.5^2}{4} = 23.125$

Dissim C-D: $\frac{7.5^2 + 0^2 + 5^2 + 0.5^2}{4} = 20.375$

Dissim C-E: $\frac{0.5^2 + 7^2 + 7^2 + 0^2}{4} = 24.5625$

Dissim C-F: $\frac{7.5^2 + 0.5^2 + 6.5^2 + 6.5^2 + 0.5^2}{5} = 28.25$

Dissim D-E: $\frac{0.5^2 + 1^2 + 0.5^2 + 0^2}{4} = 0.375$

Dissim D-F: $\frac{0^2 + 0.5^2 + 0.5^2 + 1^2}{4} = 0.375$

Dissim E-F: $\frac{0^2 + 1^2 + 0.5^2 + 0.5^2}{4} = 0.375$

We can see that A-B-C and D-E-F are two distinct neighborhoods with $\eta = 1$. Given this, we impute the missing values by taking the average of the neighbors at the column where an observation is missing.

In [55]:
inv_mask = ~(mask.astype(bool))
mask

array([[1., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0.]])

In [56]:
data

array([[1. , 2.5, 7. , 1. , 3.5, 7.5],
       [1. , 3. , 8. , 1. , 3. , 8. ],
       [0. , 3.5, 8.5, 2. , 3. , 7.5],
       [7.5, 3.5, 1. , 7. , 2.5, 1. ],
       [8. , 3. , 1. , 8. , 3. , 1. ],
       [7.5, 3. , 2. , 8.5, 3.5, 0. ]])

In [57]:
data_imputed = data.copy()
data_imputed[0, 2] = 8.25
data_imputed[1, 0] = 0.5
data_imputed[2, 5] = 7.75
data_imputed[3, 2] = 1.5
data_imputed[4, 0] = 7.5
data_imputed[5, 5] = 1

In [44]:
# these are the imputed predictions
pred = data_imputed[inv_mask]
pred

array([8.25, 0.5 , 7.75, 1.5 , 7.5 , 1.  ])

In [84]:
# this is the ground truth
truth = data[inv_mask]
truth

array([7. , 1. , 7.5, 1. , 8. , 0. ])

In [85]:
# the mse is:
mse(pred, truth)

0.5625

When we compute the MSE of the prediction by hand following Li 2019's method, we get 0.5625. Now we compute it using our implementation.

In [86]:
inds = np.nonzero(inv_mask)
A_hat = estimate_li_nn_inds(data_full, mask, eta = 1, v_inds = inds)
pred = A_hat[inds]
mse(pred, truth)

0.5625

## Cross Validation for $\eta$

Next, we implement cross-validation for the $\eta$ radius parameter. Given a dataset, an error metric, and an estimation function, we evaluate a range of values of $\eta$.

In [ ]:
# notes
    # we are only interested in the estimates that `estimate` makes for the
    # validation set in particular. For any validation fold, we must only consider observed values (need a ground truth)
    # We mask over these values to estimate, then extract the estimates using the original mask to compute the error.

In [89]:
def cross_validate_nn(Z, M, k, eta, estimate, error_metric):
    """
    Performs k-fold cross validation on using dataset `Z`, mask `M`, parameters `k` and `eta`,
    estimation function `estimate`, and error `error_metric`
    """
    # find observed indices and create splits off of those
    obvs_inds_x, obvs_inds_y = np.nonzero(M)
    
    # shuffle the x and y coordinates in the same way to maintain valid coords
    shuf_inds = np.arange(len(obvs_inds_x))
    np.random.shuffle(shuf_inds)
    shuf_obvs_inds = np.array((obvs_inds_x[shuf_inds], obvs_inds_y[shuf_inds]))
    # split coordinates into k-folds
    folds = np.array_split(shuf_obvs_inds, k, axis = 1)
    tot_error = 0
    for i in range(k):
        # indices of the observed outcomes in the validation set in this iteration
        folds_ind = tuple(folds[i])
        # ground truth
        val_data = mean_collapse(Z[folds_ind], d = 1)
        est_mask = M.copy()
        # hide observed values in the validation set
        est_mask[folds_ind] = 0
        A_hat = estimate(Z, est_mask, eta, folds_ind)
        # extract validation points
        est_val = A_hat[folds_ind]
        tot_error += error_metric(est_val, val_data)
    # return average error over k folds
    return tot_error / k

### Cross validation for Li (2019) NN

We use k-fold cross validation to tune hyperparameter $\eta$ for the Li (2019) NN model implemented above. We show results using k = 5 and k = # observed outcomes (LOOCV).

In [14]:
# first, compute dissims from a subsection of the data to get a sense of the range of distances
# notation: should change later, but M_hs is Z and A_hs is M
from itertools import product
rnd_ind = np.random.choice(37, size = 10, replace = False)
all_combs = product(rnd_ind, rnd_ind)
M_hs_collapse = mean_collapse(M_hs)
for u, v in all_combs:
    print(dissim_row(M_hs_collapse, A_hs, u, v))

0.0
1663.7362075617282
9433.312114197533
10708.135159465019
3178.353780864197
3858.7409979423865
2767.0774911816584
3845.4449588477364
2566.7926587301586
909.1473765432097
1663.7362075617282
0.0
3244.6373456790116
9885.76822916667
2104.8924575617284
4078.115162037037
1253.3985339506173
6343.9231701940025
2608.8954046639233
101.36844135802468
9433.312114197533
3244.6373456790116
0.0
13604.630401234566
1551.4845679012344
437.0987654320986
10156.326003086417
368.42669753086415
4308.5841049382725
64.90432098765433
10708.135159465019
9885.76822916667
13604.630401234566
0.0
3497.620627572016
7706.397376543211
460.83024691358025
6202.21965020576
9439.857561728395
13153.720061728394
3178.353780864197
2104.8924575617284
1551.4845679012344
3497.620627572016
0.0
2734.4951774691353
910.4014274691356
8328.937885802468
4025.8326581790125
5520.264274691359
3858.7409979423865
4078.115162037037
437.0987654320986
7706.397376543211
2734.4951774691353
0.0
8106.286779835391
1154.5992283950616
905.4911265432096
5356.809220679013
2767.0774911816584
1253.3985339506173
10156.326003086417
460.83024691358025
910.4014274691356
8106.286779835391
0.0
2192.581349206349
1833.7356288580245
129.33063271604937
3845.4449588477364
6343.9231701940025
368.42669753086415
6202.21965020576
8328.937885802468
1154.5992283950616
2192.581349206349
0.0
2942.9047496570643
226.33281893004113
2566.7926587301586
2608.8954046639233
4308.5841049382725
9439.857561728395
4025.8326581790125
905.4911265432096
1833.7356288580245
2942.9047496570643
0.0
2981.008487654321
909.1473765432097
101.36844135802468
64.90432098765433
13153.720061728394
5520.264274691359
5356.809220679013
129.33063271604937
226.33281893004113
2981.008487654321
0.0

In [92]:
# try using HeartSteps data with eta 10 to 500? are there other hyperparameter optimizations to use? 
# k = 5
eta_range = np.arange(10, 510, step = 10)
#eta_range = [350.]

min_error = float("inf")
best_eta = 0
for eta in eta_range:
    error = cross_validate_nn(M_hs, A_hs, 5, eta, estimate_li_nn_inds, mse)
    print("Error for eta " + str(eta) + ": " + str(error))
    if error < min_error:
        min_error = error
        best_eta = eta

Error for eta 10: 4470.526945546737
Error for eta 20: 4475.536943415636
Error for eta 30: 4476.936157196134
Error for eta 40: 4471.450330926661
Error for eta 50: 4523.235176899617
Error for eta 60: 4479.808514651309
Error for eta 70: 4441.046044082525
Error for eta 80: 4482.697518328679
Error for eta 90: 4671.896733367627
Error for eta 100: 4684.731098630706
Error for eta 110: 4621.9614494813095
Error for eta 120: 4632.585121579831
Error for eta 130: 4604.341967029198
Error for eta 140: 4545.1265629439795
Error for eta 150: 4591.403307962594
Error for eta 160: 4602.311572546172
Error for eta 170: 4556.604497847468
Error for eta 180: 4553.882384075544
Error for eta 190: 4626.332304131758
Error for eta 200: 4542.30245564827
Error for eta 210: 4595.234190163875
Error for eta 220: 4546.3780593309075
Error for eta 230: 4553.129749538506
Error for eta 240: 4571.724398543994
Error for eta 250: 4586.534017165392
Error for eta 260: 4387.331505732779
Error for eta 270: 4388.360103636281
Error for eta 280: 4362.348461039391
Error for eta 290: 4506.174937122709
Error for eta 300: 4325.240043599588
Error for eta 310: 4342.1005003820665
Error for eta 320: 4473.472897960604
Error for eta 330: 4239.990969006008
Error for eta 340: 4385.805326146763
Error for eta 350: 4463.717034557726
Error for eta 360: 4384.333720397346
Error for eta 370: 4249.8485262782915
Error for eta 380: 4318.80968752529
Error for eta 390: 4316.084349095905
Error for eta 400: 4403.487487254526
Error for eta 410: 4333.043457033504
Error for eta 420: 4379.960996343901
Error for eta 430: 4281.196151100823
Error for eta 440: 4348.850021022591
Error for eta 450: 4315.2732686239415
Error for eta 460: 4335.6966240796355
Error for eta 470: 4440.870511678297
Error for eta 480: 4327.826974626011
Error for eta 490: 4331.162477393956
Error for eta 500: 4351.596185593237

In [87]:
# k = # observed entries
k = len(np.nonzero(A_hs)[0])
min_error = float("inf")
best_eta = 0
for eta in eta_range:
    error = cross_validate_nn(M_hs, A_hs, 50, eta, estimate_li_nn_inds, mse)
    print("Error for eta " + str(eta) + ": " + str(error))
    if error < min_error:
        min_error = error
        best_eta = eta

<class 'float'>
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 206.   0.   0. 228.
  398. 483. 312.  23.   0.   0.   0.   0.   0.   0.   0.   0. 130.   0.
    0.  71. 182.   0.   0.   0.   0.   0.]
 [ 30.  33.  60. 137.  83.  52.  82.  67.  25.   0. 105.   0.  50.   0.
    0.   0.   0.  27.   0.   0.  35.   0.   0.  48.  12. 113.  52.  32.
    0.  16.   0.   0.   0.   0.   0.   0.]
 [154.  37. 381. 117. 241.   0.   0.   0.   0.   0.  48. 492. 208.  68.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 146.   0.   0.
  202. 157.   0.   0.   0.   0.   0.   0.]
 [101. 218.   0.   0.  45. 162.   0. 172.  52.  34.  25.   0.   0.   0.
    0.   0.  52. 137.  81.  86.   0.  33. 123. 106.   0.  20.   0.   0.
    0. 168.  82.   0.   0.   0. 111.   0.]
 [ 70.   0.   0.   0.   0.   0.  89.  98.   0. 150.  55.  28.   0.  45.
    0.   0.   0.   0.   0.   0.   0.  19.  19.  19.   0.  18.   0.   0.
    0.   0.  20.   0.   0.  50.  21.   0.]
 [  0.   0.   0.   0.   0. 156.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  76.   0.   0.  25.  66.  28.   0.  19.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  35.   0. 434. 527. 534. 122.   0.   0.
    0.  21.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  52.   0.   0.   0.  42.   0.]
 [  0.   0. 339. 218.   0.  33.  32.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   19.   0.   0.  56.   0.   0.   0.   0.]
 [ 23.  25.  28.  37. 245. 206. 106.  71.  40. 225.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   51.  41.  90.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  21.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  19.   0.   0.]
 [ 69.   0.   0.   0.   0.   0.   0.   0.  89. 549. 124.   0.  78.   0.
   62.   0.   0.  77.  60.   0.   0.   0. 116.  73.   0.   0. 166. 307.
  526.  79.  94.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 345. 389.   0.   0. 220.   0.   0.   0.  57. 186.
    0.   0.   0.   0.   0.   0.   0. 247. 321. 423. 587. 553. 128.   0.
    0.   0.   0.  54.   0.   0.   0.   0.]
 [ 30. 129.  22. 132.  81.   0.  43. 131.  27.  12.   0.   0.  38.  21.
   77. 132.   0.  40.  81. 120.  61.   0. 159.  24.   0.  95.  68. 109.
   42. 151.  96.  36.  83.   0.  92. 106.]
 [181.   0.   0.   0.   0.  58.   0.   0.   0.   0.   0.   0. 256. 350.
  104.  53. 161.  25.   0.   0.   0.   0. 102.   0.   0. 137.   0.   0.
   87.  32.  46.   0.  43.   0.   0.  48.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 32.   0. 135.  42.  47.  52.   0.  75.  25.  14.  34.   0.  19.  28.
   47.   0.  26.  63.   0.  72.  83. 278. 522. 391. 494. 486. 468. 449.
  499. 314.  12.  62.  37.   0.  24.   0.]
 [ 85. 134.  46.  60.  46. 206.  33.  73. 161. 129.  71. 210.  11. 130.
  191.  32.  43. 182. 165.  24.   0.   0.  80.  53.  86.   0.  83.  24.
    0.  37.   0.   0.  51.  41.  63.  25.]
 [  0.   0.   0. 226. 129. 109. 114. 304. 219. 108.  53.  54.  61. 114.
   30.   0.   0.   0.   0.   0.   0.   0.   0.   0. 128. 286. 391. 282.
  176.  45.   0.  68.  18.  94.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 356. 256. 216. 225. 122. 346. 386.
  343. 325. 317. 249.  16.   0.   0.   0.   0.   0.   0.   0.   0.  12.
    0.   0.   0.   0.   0.  19.  18. 102.]
 [ 44.  18.  38.  35.   0.  23.  95. 231.  33. 146. 118.   0.  42.  14.
    0.   0.   0.   0.  62.   0.   0.   0.  97. 389.  64.   0.  66. 130.
   52.  47.   0.   0.   0.   0.  57.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[174.  41.  50.  71.   0.  24.   0.  19.   0.  66. 120.   0.   0.  84.
   13.   0.  60.  18.   0.   0.  22.  81.  71. 118.   0.  82.   0.   0.
  166.   0.  29. 166. 202. 112. 147.   0.]
 [  0.   0.   0.   0. 173.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 140.   0.   0.   0.   0.]
 [151. 141.   0.   0.   0.   0.   0.  22.   0.   0.   0.  43.   0.  25.
    0.   0.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   77.   0.   0.   0.   0.   0.   0. 216.]
 [  0. 267. 285.   0.  23.   0.   0. 141. 321.   0.   0. 496. 124.   0.
    0.   0. 177. 562. 197.   0. 182. 520. 526. 348. 325. 259. 139. 134.
  226.   0.   0.   0.  42.  78.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  66.   0.   0.  26. 193.   0.   0.   0.   0. 116. 362. 147.   0.
    0.   0.  19.   0.   0.  21.   0.   0.]
 [ 36.   0.   0.   0.  36.   0.   0.   0.   0.   0.  78.   0.  21.  18.
   57.   0.   0.   0.   0.  60.   0. 115.   0.  18. 126.   0.   0. 220.
   89.  50. 155. 156. 209. 414.  76. 168.]
 [  0.   0.   0. 168.   0.   0.   0.   0.   0.   0.   0.   0.   0. 187.
    0.   0. 278.   0.   0.   0.   0.  29.  52.  48. 158.   0.   0.  41.
   46.  20.  62.   0.   0.  84.   0.   0.]
 [ 21.   0.   0.  27.   0.   0.  84.  28. 133.  14.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  13.   0.   0.   0.   0. 157. 177.  18.  85.   0.   0.
    0.  33.   0.   0.   0.   0.  23.   0.   0.   0.   0.   0.   0.   0.
   47. 317. 163.   0.   0.   0.  98.   0.]
 [  0.  80.  58.   0.   0.   0.  23.  14.  26.   0.   0.   0.  40.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  82.  39.   0.
   13.  74.  29.  72.  41.   0.   0.  30.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 104. 153.   0.   0.  71.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   22.  39. 183.  82.   0.   0. 140. 219.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  68.  49.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 143.
  314.   0.   0.  34.  47.   0. 147.  28.  85.  18.  31.   0.   0.   0.
    0.   0.  22.   0.   0.  73.  59.  48.]
 [  0.   0.   0.   0.   0. 143. 423. 555. 412.   0.   0.  14.   0. 131.
   61.   0.   0.  17.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   22.  75.  64. 293.   0.   0.   0.   0.]
 [105.  44.  80. 120.   0.   0.  38.  41.  19.  20.   0.   0. 317. 551.
   52.   0. 403. 465.  14. 254. 519.  63.   0.  16.   0.   0.   0.   0.
    0.   0. 190.  16.  20.   0.   0.   0.]
 [  0. 139. 157.   0.   0.   0.   0.   0.   0.  22.   0.   0.   0.   0.
  471. 126.   0. 475. 442. 375. 136. 744.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 237. 515. 519. 505. 490. 498.  41.
    0.   0.  98.  69.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  91.  39.  82.   0.   0. 246.]
 [  0.   0.   0.  46.   0. 121.  21.  42.  76. 137.  75.   0.  21.   0.
    0.   0.   0.  29.   0.   0.   0.   0.   0.  22.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 199. 526. 533. 190.   0.
    0. 117.   0.   0.   0.   0.   0.   0.   0.   0.   0.  51.   0.   0.
    0.   0.   0.   0.   0.   0. 153.  15.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  40.  23.   0.   0.   0.   0.   0.   0.   0.
   82.   0.   0.  32.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0. 236.  45.   0.  12.  74.   0. 141.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  31. 120. 513. 510.
  526.  75. 153. 516. 413.  18. 146. 386.]
 [228.  93.   2.   0.   0.  39.   0.  26.   0. 150.  12.  21.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  20.]
 [  0.   0.   0.   0.   0. 118.   0.   0.   0.   0.   0.   0.   0.  39.
   55.   0.   0.   0.   0.   0.   0.  15.  71. 169.  23.   0.   0.   0.
    0.   0.  53. 121.  66. 152.  20.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 145. 353. 288. 394.  49.   0.   0.   0.   0.   0.   0.
    0.   0. 174.   0.   0.   0.  87. 203.  19.  77.  56. 140.  34.  44.
    0.  24.  74.  74.   0.  38.   0.   0.]
 [142. 117. 110.   0.   0.  24.  77.   0. 177.   0.   0.   0. 166.  62.
    0.   0.   0.   0.  23.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   42.  50.   0.  18. 138.  63. 112. 215.]
 [  0.  28. 109.   0.   0.   0.  55.   0.  21.  19.  52.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  46.  45.   0.  19.   0.   0.   0. 155.  35.  25.  23.
   64. 137.  76.   0.   0.   0.   0.  97. 140. 154.   0.   0. 176.   0.
  149.   0.  86.  94.  34. 115.   0.   0.]
 [ 63.  36.  46.  45. 110.  43.  92.  26.  48.   0.   0.  61. 212. 337.
  179. 235.  82.  33. 150.  79.  64.  96.  65. 196.  50.  48. 116. 241.
   20.   0.   0.  40.  26.  96.  31.  62.]
 [  0.  93.   0.   0. 255.   0.   0.  21.   0.   0.   0.   0.   0. 196.
  202.  84.  24.  40.   0.   0.   0.   0.   0.  75. 148. 416. 217. 226.
   21. 296. 189. 247. 354. 184. 268. 107.]
 [192.  25.   0.   0.   0.   0.   0.  79. 143.   0.   0.   0.   0.   0.
    0.  97.   0.  13.   0.   0. 192.   0. 288. 503. 574. 476. 378.   0.
   58.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 277.   0.   0.   0. 170.   0.   0.   0.  54.  72. 176.
  119.   0.  59.   0.  39.  59.  23.  25.  54.  71.  96. 211. 123. 348.
    0. 150.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 106.   0.   0.  54.   0.  62.   0.   0.   0.   0.   0.
    0.   0.  19.   0.   0.   0.  53.   0.]
 [  0.  19. 132.  80. 270. 560. 562. 270.  74. 235.   0.   0.   0.   0.
   20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  23.   0.   0.   0.   0. 214.]
 [  0.  66.  81.  49.  11.  66.  14.   0.   0.   0.   0.   0.   0.  63.
    0.  34.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  35.   0.
    0.   0.   0.  54.  26.   0.   0.   0.]
 [  0.   0.   0.  31. 480. 536. 425.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 101.  81.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 131. 192. 135. 167.   0.   0.   0.   0.   0.   0.  25.   0.   0.
    0.   0.   0.   0.   0.   0.  53.   0. 117.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  18.   0. 145.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 112. 263.  61.   0.   0.   0.   0.  74.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  24.   0.   0.   0.]
 [176. 472. 516. 369. 232.  75.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 136. 262.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0. 284. 195.  43.  67.  19.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 157.
  285.   0.   0.   0.   0. 164. 144.  65.]
 [ 20.   0.   0.   0.  45.   0.  70.   0. 130. 563. 517. 567. 561.  56.
   16. 221.   0.   0. 103.  22.  35.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  38.   0.  26.]
 [472. 524. 342.   0.   0.   0.   0.  51.  94.   0.  24.   0.   0.   0.
   34.   0.   0.  21.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  18. 442. 509. 416.  77.  67.  71.]
 [  0.  27. 291.  45. 144.  95.  29.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  22.   0.   0.  41.   0.   0.   0.]
 [ 47.  40.   0.  43.   0.  90.   0.   0.   0.   0.  18. 200.  53.  64.
   18. 383. 564. 564. 533. 299.  26.  29. 501. 558.  72.   0.   0. 112.
   37.  33.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 76.  14.  40. 111.  46.  40.   0.  93.   0.   0.   0.   0. 107.   0.
    0.   0.   0. 152. 129.   0.  65.  99.  75.   0.  93.  18.   0.   0.
   99.  14. 175.  19.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 225.   0.   0.  49. 285. 286. 239. 248. 217. 124.   0.  82. 116.
   43. 322. 516. 509.  47.   0.   0. 137.]
 [104.  18.  29.   0.   0.   0.   0.   0.   0.  24.  89.  83. 182. 337.
  263. 486. 402. 388. 442. 436. 416. 516. 546. 391. 263.   0. 278.  70.
   51.  67.  21.  45.   0. 248.  19.  20.]
 [528. 454. 202.   0.   0.   0.   0.   0. 175. 161. 106.   0.   0.   0.
   23.   0.   0.  19.   0.   0.   0.   0.   0.   0. 110.  30.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [213.  18.   0.   0.   0.   0.   0. 118. 152.  85. 194.   0.   0.   0.
  117. 191.  91. 188. 115. 288. 169.   0.   0.   0.   0.   0.   0.  76.
    0. 194.  40.   0. 118.   0.   0. 107.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  146.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 368. 575. 505.   0.  33.   0.   0.]
 [  0. 125. 143.  88. 176. 168. 107. 142. 146. 239. 264.  51. 178.   0.
   77. 201. 253. 114. 121.  83.  34.  32.  92. 176. 257. 238.  83.   0.
    0.   0. 105.  56.  71.   0.  57.  85.]
 [  0.   0.  76.   0.   0.   0.   0.  36.  22.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   43.   0.  25.  60.   0.   0.   0.   0.]
 [286. 131.   0.  27.  21.  24.   0.   0.   0.  71. 432. 100.  32. 164.
   23.  30.   0.   0.  44. 431. 227. 148. 178.  85.  40.  61.  47.  61.
    0.   0.   0.  25.   0.  27.   0.   0.]
 [184.   0.  38. 106. 143.   0.   0.  37. 165.   0. 103.   0.   0. 104.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.  23.   0.   0.  39. 115. 104.  97.  35.
    0.   0.   0.   0.  43.   0.   0.   0.   0.   0.   0.   0.  76. 124.
  162.   0. 248.  62.  26. 236. 208.  27.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 107.
  238.   0. 454.  78.  60.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 75.   0.   0.  17.   0.  30.   0.   0.   0.   0.   0.  85. 149.   0.
    0.   0.  18.  71.  31. 289.   0.   0.   0.   0.  14.  34.  24.   0.
    0.  43.   0. 114.   0.  24.  27.   0.]
 [  0.  46.  33.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  40.  27.   0.  22.  29. 179.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  77.   0.   0.   0.
   72.   0.   0.   0.   0.   0. 260. 517.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  47.   0.   0.   0.   0.   0.   0.  72.
  204.   0.   0.  39.   0.   0.   0.  11.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 327. 165. 401. 498. 521. 348. 389. 430. 408. 266. 260. 424.  74.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 65. 160. 149. 198. 126.  17.  44.  89. 178.  89. 301. 512. 417. 178.
   45.   0.  29. 100.   0.  65. 588. 534. 761. 368.  38.   0.  37. 121.
   27.  19.  42.  22.  76. 238.  85. 136.]
 [ 12.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  20.
  295.  21.   0.  26.   0.   0. 235.   0.   0.   0.  25.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  11.   0.]
 [  0.   0.   0.   0.  97. 109.  67.   0.  31. 130. 452. 606. 265.   0.
    0.   0.   0.   0.   0. 163.   0. 403. 316. 230. 380.  27.   0.   0.
  115. 581. 172.  20.   0.   0.   0.   0.]
 [377. 509.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  23. 174. 460. 382.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 156. 584. 524. 205. 246.   0.   0.  22.   0. 113. 142.   0.   0.
   49. 136. 308. 468. 563. 500. 378. 120. 190. 493. 581. 226.   0.  25.
   48.  44.  45.   0.   0.   0.   0.   0.]
 [  0.  16.   0.   0.   0.   0.   0.   0.   0.   0.  27.   0.  37.   0.
   41.  29.   0.   0.   0.   0.   0.   0.   0.  13.   0.  98.  67.   0.
   45. 105.  43.   0.  13.   0.   0.   0.]
 [  0.  32.  25.  34.  43. 188. 191.   0.  83. 235.   0.  56.  55.  59.
    0.   0.  56.   0.   0. 236. 113.   0.   0.   0.   0.   0.   0.  77.
   73.   0.   0.   0.   0.   0.   0. 128.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 102. 114. 277. 126.  47.  71.  54. 108.
   37.  74.   0.  58.  48. 292. 138. 212. 251.   0. 206. 155.   0.   0.
    0.   0.   0. 210.  81.   0.   0.   0.]
 [  0. 104.  63.  98.  46. 148. 145. 105.   0. 100.   0.  28.   0.  32.
   11.   0.  18.  32.  45.   0.  18.   0.  37. 157. 129.  46.  23.  22.
    0.   0.   0.  21.   0.   0.  19.  53.]
 [577. 338. 397. 447.  25.   0. 544. 522.   0.   0.   0.   0.   0.   0.
    0.  36. 150.   0. 351.  52.   0.  27. 413. 426. 458. 490. 473. 482.
  386.  87.   0.  33. 185.   0.  14.   0.]
 [212. 232. 530. 183. 556. 127.   2. 262.   0.   0. 214.   0.  55.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  64.   0.
    0.   0.   0.   0.  18. 406. 580.  74.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  83.  47.  27.   0.
    0.   0.  59.   0.  94.  64.  18.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  25.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.  49. 154.  43.  29. 280. 156. 138.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  18. 207.   0.  86. 134.
  180.  24.   0.   0.   0.  19.  28.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 80.   0.   0.   0.   0.   0.   0.  47.   0.   0.   0.   0.   0.   0.
   43. 156. 136.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  28.
    0.  21.  61. 128. 108.  31.   0.   0.]
 [  0.   0.  44.  32.   0.  28.  58. 122.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  26.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [461. 111.  73.   0. 146.  33.  84.   0. 217. 445. 496. 479.  58.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 129.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  53.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  23.   0.   0.]
 [  0. 136.   0.   0.  18.   0.   0.   0.   0.  70.   0.   0.   0.   0.
    0. 119.   0.   0. 110.  73. 104.   0.   0. 120.   0.  78.  40.   0.
   96.  24.   0. 355. 164.  93. 114.  37.]
 [252.   0.   0.   0. 210. 134.   0.   0.   0.   0.   0.   0.   0.   0.
   28.   0.   0.   0.   0.   0.   0.   0.   0.   0. 168.  85.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [239.   0.   0. 520.  57.   0.  48.   0.   0.  11. 109.  21.  59.   0.
    0.   0.  18.   0.   0.  49.   4.  18. 116. 582. 375.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  31.]
 [180.  28.   0.   0.   0.  75. 258.  52.  40. 519. 491. 523. 486. 459.
  505. 528. 579. 445. 212. 258.  61.  83. 223. 340.  32. 508. 498. 407.
  491. 479. 448. 207. 129.   0.   0. 115.]
 [  0.   0. 177. 207. 224. 170. 202.  86.  33. 191. 207.   0.   0.   0.
    0.   0.   0.   0.   0.  58.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  73.  78.   0.]
 [433. 160. 162.  56. 181. 491.  97.  82. 176. 445. 511. 208. 182.  62.
   42. 196.  19. 108. 146.  60. 474. 483. 308. 162.   0.   0.   0.   0.
  442.   0.   0.   0.   0.   0.   0.  91.]
 [  0.   0.  45.   0.   0.  63.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  35.  48.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  19.  57.  29.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  27.  59.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  22.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 19.  47.   0.   0.   0.   0.  40.   0.   0.   0.   0.   0.  53. 127.
   91.  41.  18.  24. 158. 228.   0.   0.   0.   0.   0.   0.   0.   0.
  137.   0.   0.   0.   0.   0.   0.   0.]
 [222.   0.   0.   0. 209.  67.   0.   0.   0.   0.   0. 209.  19.   0.
    0.   0.   0.   0.   0.   0.   0.   0. 167.   0.   0.  11.   0.   0.
    0.   0.   0.   0.  19.   0. 134.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 196. 559.
  526.   0.   0.   0. 128.   0.   0.   0.   0.   0.  36.  18.  95.   0.
   30. 124.   0. 329. 256. 124. 110.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  43.  70.
   40.   0.   0.   0.   0.   0.   0.   0.   0.   0.  35.  63.  69. 436.
  112.   0.  62.  62.  50.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  52.   0.  64.  21.  42.  18.  83.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  47.  54.   0.
    0.  70.  21.  84.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 30.  34. 272.  42. 116. 190. 136.  35.  75.   0.  13. 144.  55. 113.
   21.   0.   0. 126.  44.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  81.   0.  34.   0.   0.]
 [534. 221.  51.  38. 164. 101. 125.  66.  72.  98. 130.   0.   0.  44.
    0.  74.  57.   0.  75.  89. 107. 142.  24.   0.  72.  52.  18.  46.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 181.  62.   0.   0.   0.   0. 345. 419.   0.   0.   0.   0. 429.
  211.   0.   0.   0.   0.   0.   0.   0.]
 [ 23.   0.   0.   0. 256.  84. 124.   0.   0.   0.   0. 200.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  28.   0. 271.   0.   0.   0.   0.
    0.   0.   0.  86. 239. 325.  22. 126.]
 [  0.   0.   0.   0.   0.   0.   0.  62.   0.  60. 170.  28. 326.  25.
    0.   0.   0.   0.   0.  92.  21.  57.   0.  25. 135.  22.   0.   0.
   72.  32.  70.  70. 108.  68.  25.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  24.  27.   0.   0.   0.  40.  46.
   69.  45.  25.   0.   0.   0.   0.   0.   0.   0.   0. 170.   0.   0.
    0.   0.   0.  51.  22.   0.   0.   0.]
 [  0.  12.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   38.  23.   0.   0.  15.   0.   0.  82.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  44. 350.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 108.
  369.   0.   0.   0.   0.   0.   0.  62.]
 [148.   0.  29.  88.   0.   0.   0.  20. 142.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  76.  20.   0.  20.  26.  45.   0.   0.
    0. 140.   0. 419. 123. 221.  41.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  15.   0.   0.   0.   0.   0.
    0.   0.   0.  21.   0.  26.  33.  60.]
 [111.  52.   0.   0.   0.   0.   0.  16. 139.  16.   0.   0.   0.  47.
  114.   0.   0.   0.   0.  21.   0. 131.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 107.  79.]
 [  0. 108.   0.  24.  50.   0.   0.   0.   0.   0.  25.  49.   0.   0.
    0.  82.   0.   0.   0.  41.   0.   0.  21. 111.   0.   0.  27.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 67.  29.  22.   0. 344. 363.   0.  32.   0.   0.   0.  24.  77. 319.
    0.   0.   0.  18.   0.   0.   0.   0. 258.   0.   0.   0.  20. 359.
  388.  50.   0.   0.   0.   0.   0.  90.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  40.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  44.   0.  39.   0.]
 [140.  22.   0.   0.   0.   0.   0.   0.   0.  81.  18.   0.   0.   0.
    0.  25.  41.  94.   0.   0.   0.   0.   0.   0.   0.   0.  94.  20.
   24.   0.   0.   0.  26.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  90.  16.   0.   0.  92.   0.   0.
    0.   0.   0.   0.   0.   0.  27. 153.  30.  30.  73. 122. 106.  60.
   58.   0.   0.   0.   0.  65. 156.  57.]
 [ 75.   0.  12.   0.   0.   0.  25.  48.   0.   0.   0.   0.   0.   0.
   60.  18.   0.  15.  21.  15.   0.  11.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  24.   0.  24.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  56.   0.   0.   0.   0.  53.   0.
   37.  44.  25.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   55.  70.   0.   0.  37.  18.  82. 287.]
 [  0.   0.   0.   0.   0.   0.  78. 100.  38.  19.  21.  98.  31.   0.
   80. 136.  36.   0. 226. 118.   0.  18.  19.  61.  92.  46. 104.  86.
   35. 112.   0.   0.   0.  40.   0.   0.]
 [  0.  21.  34.   0.   0.   0.   0. 159.   0.   0.   0.  72.   1.   0.
    0.   0.  11.   0.   0.   0.   0.  80.  14.  22.  26.   0.  81.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[247. 121. 194. 261. 263. 219. 125. 245.  67. 173.  58.  91.   0.  71.
  109.   0.   0.   0.   0.   0. 103.  28.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 152. 568. 353.
  255. 289. 602. 557. 557. 483. 527. 510. 554. 129. 238. 176.   0. 382.
  269.   0.   0.   0.   0.   0.   0.  77.]
 [  0. 150. 475. 385. 767. 540. 477. 503. 706. 536. 178. 122. 542. 345.
    0. 121. 122.  67.   0.   0.   0.   0.   0.  20.   0.   0.   0.  30.
    0.   0.   0.   0.  42.  50.  97.   0.]
 [ 31.  39. 382. 561.  71. 203. 354.   0.   0. 486. 245.   0.   0.   0.
   14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  54. 354. 313. 430.  76. 242.]
 [528.  87.   0. 287. 425.  92. 115.  23.   0.   0.   0.   0.   0.   0.
   53.  73.   0.   0. 374. 509.   0.  24. 320. 119. 211. 403. 558.  30.
   95.   0.  20.  87.   0.   0.   0.   0.]
 [  0.   0.   0.  13.  99. 606. 241.   0.  14.   0. 204. 163. 136.  96.
   69. 142. 227.   0.   0.   0.   0.   0.   0.  61.  59.  81. 114.   0.
    0. 539. 549.  53.  14.   0.   0.   0.]
 [  0.   0.   0.   0.  42.   0.   0.   0.  30.   0.   0.  32.  51.   0.
   33. 216. 201.   0. 134.  27.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  46.   0.  25.   0.  25.  42.   0.  55.  76.  35.   0.   0.
    0.   0. 112.   0.   0.   0.   0.   0.   0.   0.  36.  86.   0.   0.
    0.   0.   0.   0. 133.   0.  67.  59.]
 [  0.  21.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.   0.  53.
   38.  60.   0.  25.   0.   0. 358.   0.   0.  75.  93.   0.   0.   0.
    0.  35.  20.  43.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 183. 498. 489. 441.
  491. 506. 414.   0.   0.   0.   0.   0.  21.  35.   0.   0. 451. 463.
  305.  26.   0.   0.   0.   0.   0.   0.]
 [  0.  34.  36. 101.   0.  45.  22.  90.  49.  86.   0.   0.   0.  33.
   61.  14.   0.   0.  18.  27.   0.   0.   0.   0.  19.  95.   0.  23.
  251.  30. 156. 125.  21.  89.  19.  81.]
 [  0.   0. 160.   0.  97.  62.   0. 227.  14.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   67.   0.  79.   0.   0.  88. 208.   0.]
 [126.   0.  83.   0.   0. 104. 121. 142.   0.   0.   0.   0.  82.  19.
   51. 123.   0.   0.   0. 187. 421. 313.  16.   0.   0.   0.  97.   0.
    0.   0.  17.  49.   0.  19.   0.   0.]
 [  0. 268.   0.   0.   0.   0.  61.   0.   0. 242.   0.   0.  24.   0.
    0.   0.   0.   0.   0.   0.   0. 198.  13.   0.   0.   0.   0.   0.
    0.   0.   0. 134. 117.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  34.   0.   0.   0.   0.
    0.   0.   0.  96.   0.  53.   0.  41.   0.   0.   0.   0.   0.  71.
  148.   0.   0.   0.   0.  42. 199. 141.]
 [  0.  91. 246. 258. 339.  87.   0.   0.   0.   0.   0.  53.  26.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  29. 196.  53.
   19.   0.   0.  24.  25.   0.  81.   0.]
 [ 25. 283.   0. 238.   0. 212.   0.   0.   0.  38. 171.   0.   0.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  68.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  110.   0.  92.  21.   0.   0.   0.   0.   0.   0.   0.   0.   0. 101.
  166.  82. 150.   0.  37.  75.   0.   0.]
 [  0.  64. 114.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 165. 174. 192.  42.   0.   0.   0.   0.
    0.   0.  31.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  81. 105.
  271.  76. 459.  17.  73.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  13.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 39.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  20.  89.   0.   0.   0.  28.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  94.   0.   0.   0.   0.   0.   0.
    0.  86.   0.   0.   0.   0.   0.  42.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  42. 126.  50.  49.   0.  49.  49.   0.   0.   0.
  139.   0.   0. 104.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 336. 308. 301.   0.   0.  41.
  203.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 145.  63.   0. 181.]
 [  0.  31.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  33. 100.   0.  36.   0.  84.]
 [ 16.   0.  44.  78.  76.   0.  52.   0.  27.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 105.  81. 152.  18.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 217. 104. 139. 161.   0.   0.   0.  59. 234.  24.
   70.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 120. 164.  12.  21.   0.  27.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  27.   0.  97.  24.  19.  25.  25.  39.   0.   0.  97.   0.   0.
    0.   0.   0.  18.   0.   0.   0.   0.]
 [  0.   0.  73.  53.  17.  26.  72.  52.  16.  79.  52.  98. 346. 114.
    0.   0.   0. 312. 476.  62.   0.   0.   0.   0.   0.  51.  51.  16.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [100.  68.  22. 363.  55.  33.   0.  43.  84. 104.  22. 246.   0.   0.
    0. 125.  98. 166.   0.   0.   0.   0.   0. 174.  70. 193.   0.   0.
  153. 253. 494. 476.  79. 110. 301. 209.]
 [  0.   0.  37.   0.   0.   0.  20.   0.   0.   0.   0.   0.   0.   0.
   60. 127.   0. 113.  54.   0.   0.   0.   0. 141.  33.  24.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 118.
   87. 242. 606. 395. 522. 655. 122. 698.  55.   0.   0.   0. 290.  95.
  253.   0.   0.   0.  73.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  84.  45.
  110. 330.   0.   0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.  44.  50.   0.   0.   0.  83.   0.   0.   0.   0.
    0.   0.   0.  18.   0.   0.   0.  18.  26.   0.   0.   0. 164.  18.
    0.  76.   0.   0.   0.   0.   0.  77.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 160. 578. 604. 357.  75.  58.
   42.   0.  44.  43.   0. 142. 165.  61. 156. 408. 478.  14.  21.  20.
  422. 482.  37.   0.   0.   0.   0. 151.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0. 181. 544. 414.   0. 298. 187.
  315. 232. 324. 572.   0. 472. 183.   0.]
 [  0.  86.  66.   0.   0.   0.  55.  39.  53.  61.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  21.  83.   0.   0.   0.   0.  50. 306.   0.
    0.   0.  55. 102.  81. 143. 163. 165.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 146.
  150.  19.   0.   0.   0.   0.   0.   0.   0.   0.  32. 207.  12.  22.
    0. 151. 108. 155.  73.  85.   0.   0.]
 [  0.   0.  35.   0.   0.   0.  41.   0.  33.   0.   0.   0.   0.  41.
  112.  41.   0.   0. 144.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   67.  83.  38. 238.  32.  31. 100. 107.]
 [ 40. 113.   0.  20.  23.   0.   0. 155. 175. 292. 103.  41.  43.  58.
    0.   0. 222.   0.   0.  24.   0.   0. 135.  28.   0.  20.   0.   0.
   20. 195.  14.   0.   0.   0.   0.  48.]
 [  0.   0. 144. 145. 349.   0.   0. 156.   0.   0.   0.  84.  30. 142.
    0.   0.   0.   0.  51.  73.  44.  80.   0.  36.  58.  90.   0.   0.
    0.  46.  23.   0.   0.  24.  84.  92.]
 [  0.   0.   0.   0.   0.   0.  58. 483. 462. 233.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 133. 113. 485. 453. 204. 136.]
 [  0.   0.   0.   0.   0.  18.   0.  43. 140.   0.   0.   0. 146.  14.
    0.   0.  24.  26. 102. 221. 237. 110. 316. 322. 153.   0.   0.   0.
    0.  18.   0.  73. 142.   0.   0.   0.]
 [153.  85. 136.   0.   0. 133. 219.  21.   0.   0.   0.   0.   0.   0.
   29. 154.  76.  29.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  38.  19.   0.   0.   0.  73.]
 [  0. 118.  29.   0.  22.  43.  42. 126.   0.   0.   0.   0.   0.  58.
   52.   0.   0.  27. 301. 108.  96.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [101.  77.   0.   0.   0.   0.  23.   0.   0.  52.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 124.   0. 100. 207.   0.   0.   0.  50. 105.
    0.  38.   0.   0.  41.   0.  60.   3.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 157.   0.
    0.  12.   0.   0.   0.   0.   0.  14.   0.   0.   0.   0.   0.   0.
    0. 108. 614.  84.   0.   0.   0. 418.]
 [ 45.   0.   0.   0.   0.   0.   0. 108.   0.  83. 112.   0.   0.   0.
  263. 138.  97.   0.   0.   0.  43.  20.  98.   0.  38.  51.   0.   0.
    0. 105. 173.  99.  66.   0.   0.   0.]
 [  0. 186.  60.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  89. 274. 140.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 27.  38.   0. 116. 535. 469. 428.   7.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  36.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  39.   0.   0.]
 [  0.   0.   0.   0.  41.  20. 183.  19.   0.   0.  23.   0.   0.   0.
  203.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 409. 159.   0.   0.   0.]
 [  0.   0.   0.  24.  21. 114.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  74.  20.   0.   0.   0.   0.   0.   0.   0.   0.  64.
   45.  39.   0.   0.   0.  38.  61.  88.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 115.   0. 215.   0.  14.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 143.   0.   0.   0.   0.   0.   0.   0. 114.
   27.   0.  19.   0.   0.  12.   0.   0.]
 [  0.  44.  42.  50.  68.  69.  95.  54. 136.  52. 207.  13. 205.  16.
    0.   0.   0.  21.   0.  18.  48. 110.  81.  25.  48.  65.  18.  17.
   26.  36.   0.  60. 241. 159.  33. 131.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  19.   0.  48.   0.  50.  13.  55.  28.  34.  34.   0.   0. 102.
   61.   0. 210. 166.   0.   0.   0.   0.   0.   0.   0.   0.  52.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 40.   0.   0.   0.   0.  42.   0.   0.  65.   0.   0.   0.   0. 238.
   36. 112.   0. 108. 180.  23.   0.   0. 315. 140.  31.   0.   0. 284.
  322. 143. 268.  42. 335.  64.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  48.   0.   0.   0.   0.  27.  24.  66.
   24.  24.   0.  45.  18.   0.   0.   0.  38.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  74.]
 [ 62.   0.  57.   0.   0.  22.   0.   0.  50.  88. 129.  43.  38.  29.
   64.   0.  91.   0.   0.  90.  73.  53. 282. 109. 190.   0.   0.   0.
    0.   0.  66. 121. 180. 102.  23.  20.]
 [ 34.   0.   0.   0.   0.   0.   0.  18.   0.  18.   8.   0.   0.  40.
    1.  34.   0.   0.   0.  46.   0.   0.  40.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  67.   0.   0.]
 [  0.   0.   0.  18.   0.   0.   0.   0.  13.   0.   0.  18.  69. 140.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 162. 303.   0.
    0.   0.  55.  21.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 109. 271. 510. 500. 511.
  196.   0.   0.   0. 172. 496.   4.   0. 122.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 107. 102.   0. 114.   0.   0.  26.
   47. 100.   0.  39.   0.   0.  51.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  38.   0.   0. 112.   0.]
 [ 20.   0.   0.   0.   0.   0.   0.   0.   0.   0.  25.  22.   0.  34.
   65.   0.   0.   0.   0.   0.   0. 230.  38.   0.  93.  38.   0. 357.
  208. 222.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  86.  13.   0.  37.
    0.   0.  23.   0.  16.   0.   0.   0.   0.  41.  12.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  60.   0.   0.   0.   0.   0.   0.   0.   0.  39.
   23.  91.   8.   0.   0.  56.  31.  68. 106.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 154. 578. 785.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  53.   0.   0. 144.  60.  21.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 367. 553.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  28.   0.   0.   0.
    0. 105.  21.   0.   0.   0.   0. 188.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 135. 142. 295. 261.  49. 168.   0.
  157. 159. 114.  49. 173. 157.  67.   0.  46.  66. 207. 205.  58.  98.
   20.   0.  27.  60.  25.   0.  80.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [202.   0. 165. 142. 116.   0.   0.   0.   0.   0.  25.  51.  13. 145.
   12.  73.   0.   0.   0.   0.   0.   0.   0.   0.  40.  77.   0.   0.
    0.   0.   0.   0.   0.  43. 240. 113.]
 [ 49.   0.   0.   0.   0.  77.   0.   0.  41.   0.   0.   0.   0.  76.
    0.   0.   0.   0.   0.   0.  37.  14.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  85.  13.   0.   0.]
 [233. 142. 343.  23.  12.   0.  93.  49.  12. 248. 212.   0.   0. 115.
  179. 125.  38.  59.  11.   0.   0.  62.   0.  36. 202.  43.  35.   0.
   14.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  43.  22.   0.   0.  40.  76.  87.   0.   0.   0.  61.  70.
   67. 160.  63.  19.   0.  90. 211.  14. 247. 102.   0.  34.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 68.   0.   0.  26.   0.  69.   0. 247.  51.  52.  26.   0.   0.   0.
    0.   0.   0.   0. 240.  45.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  83. 348. 206.   0. 115.  87.  85.   0.   0. 132. 228. 549.  19.
    0.   0.   0.   0.   0. 366. 129. 124.  45.   0.   0.   0.   0.   0.
    0.   0.   0.  61.   0.   0.   0.   0.]
 [ 54.   0.   0.   0. 158.   0.   0.   0. 197.   0.   0.   0. 217.  97.
    0.   0.   0.   0.  55.  71.  73.   0.  94.   0.  19.   0.   0.   0.
    0.   0.   0.  19.  53. 391. 230. 368.]
 [  0.   0.   0.   0.   0.   0.   0. 283. 581. 573.  84.   0.   0.   0.
   52. 184. 176.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 103. 169.  18.]
 [  0.   0.  30.   0.  37.   0.   0.   0.   0.  66. 129.  70.   0.   0.
  151.  14.  36. 121. 114.  54. 102.   0.   0.   0.   0.   0. 247. 215.
    0. 446. 282.   0.  27. 188.   0.  65.]
 [  0.   0.   0.   0.   0.   0.   0.  55.   0.   0.   0.   0.   0.   0.
    0. 121.   0.   0.  88.   0. 248.   0.   0.   0.   0.   0.  67.   0.
   29.   0.   0.   0.   0.  43.   0.   0.]
 [254. 171. 411. 106.  53. 442. 469.  17.   0.   0.   0.   0.   0. 283.
  506. 184.   0. 109. 129.   0.   0. 206.   0.   0.   0.   0.   0.   0.
  177.  14.   0.  61.   0.   0.  24.   0.]
 [142.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  40.   0.   0. 153.  28. 205. 233. 193.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20.  24.   0.   0.   0.   0.   0.   0.   0. 259. 125.  19.  60.
    0. 154. 360.  22.  49.  18.  16.  37. 217.  55.  34. 282.  41. 102.
    0.   0.   0.   0.   0. 154.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 122.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  66.  30.   0.   0.   0.]
 [  2.   0.   0.  46.   0.   0.   0.   0.  38.   0.   0.  48. 112.  22.
    0.  64.  24.   0.   0.  19. 114.  63.   0.   0. 277.   0.   0.  59.
   19.   0.   0.   0.  68. 169.   0. 235.]
 [  0.   0.   0.   0.   0.   0.  18.   0.   0.  43.   0.   0.   0.   0.
    0.  22. 587. 761. 714. 784. 747. 799. 811. 434.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  18.  15.  14.  36.  52.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  23.  28.  49.   0.
   46.  16.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  19.   0.   0.   0.   0.
    0.  96. 213. 580. 803. 350. 668. 570. 707. 585. 308. 187. 107.  91.
  321. 385. 130.  65. 163. 123. 136.  46.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 70.   0.   0.  25.  75. 149. 142. 172. 116.   0.   0.  19.   0.  19.
   47.  26.  79. 103.   0.  98.  22.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  45.   0.   0.  81.   0.  71. 112.   0.   0.   0.   0.   0.   0.
   40.  16.   0.   0.   0.   0.   0.  20.]
 [553. 129.  77.   0.   0. 152. 473.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 190. 184.   0.   0. 187.   0.  91.   0.   0.
    0.   0.  24. 543. 247.   0.   0.   0.]
 [ 95. 102.   0.   0.   0.   0.   0.   0.   0.  24.  32.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  83. 359. 128.  73. 122. 292.   3.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 32. 108. 293. 111.  36.   0.   0.   0.   0.   0.   0.   0.  19.   0.
    0.  65.   0.  50. 130.  44. 252. 240. 115.   0.   0.   0.  66.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 30.   0.   0.   0.   0.   0.  24.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  27.]
 [  0.   0.   0.   0.  19.   0. 121. 176. 123.  68.   0.  42.   0. 181.
   83.  42.   0. 193.  19.  95.   0. 190. 224.   0. 109. 182.  74. 106.
   19.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   47.   0.  25.  49.  50.  67.  57.  76.  81.  40.  62. 141.   0.   0.
    0.   0.   0.   0.   0. 134.   0.  43.]
 [181.   0.   0.   0.   0.  49.   0.   0.  20.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 163. 139.  21.   0.   0.
    0. 125.   0.  72.  80.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 136. 275.   0.   0.   0.   0.   0.   0.   0.
   78.  37.   0.   0.   0.   0.   0.   0.   0.   0.   0.  43.   0.   0.
    0.  99. 238. 116.   0.   0.   0. 328.]
 [  0.   0.   0.   0.   0.  83. 236. 126.   0.  51.  89.  19.   0.   0.
    0.   0.  40.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  23.   0.   0.   0.]
 [  0.   0.   0.  50.  46.  96.  88.  89. 118.   0.   0.   0.   0.  27.
   68.   0.   0.  59.  18. 131.   0.  24.   0.   0.   0.  64.  58.   0.
    0.  64. 146.   0.   0.  47.   0. 514.]
 [  0.   0.   0.  54.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 269. 205.  94.   0.   0. 101. 196.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 297.
  301.   0.   0.   0.   0.  16.   0.  52.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 353. 219.   0.  60.
  206. 125. 141.  48.  72.  44. 105.  94. 147. 153.  40.  59. 128. 239.
  139. 110. 143.   0.  85.   0.   0.  18.]
 [  0.   0.   0.   0.   0.   0. 136. 194.  22.   0.   0.   0.   0.  27.
    0.   0.   0. 116.  81.  54.   0.   0.   0.  32.  41.   0.  66. 373.
   24.  42.  24. 102.   0.   0.  96.   0.]
 [  0.   0. 193.  97. 219.   0. 198. 226. 456. 151.   0.   0.   0. 193.
   92.   0.   0.   0. 198. 569.  67.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  85. 346.]
 [ 15.  22.   0.   0.   0.   0.   0.   0.  23.  57. 182.  18. 241.  61.
   78. 127. 186.   0.   0.  18.  45.  98. 112. 144. 172. 212.  82. 101.
   79. 178.  26.   0.  46.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   31.  33.   0.  76.  47.  23.  92.  63. 126.   0.   0.   0.  31.   0.
   49.   0.  57.   0.   0.   0.  51.  30.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 172.  81.  19.
   16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 127.  87.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0. 345. 485. 229. 245. 698. 703. 692. 587. 557. 546. 670.
  587. 618. 536. 177. 237. 396. 378. 158.  29.  90.  21.   0. 208. 235.
    0.   0.   0.  59.  36.   0.   0.   0.]
 [  0.   0.  62.  86.   0.   0.   0.   0.  34.  20. 107.   0. 132.  84.
  112. 334.  99. 381. 162. 269. 244. 347. 360. 303.   0.   0. 284.  65.
    0.   0.   0.   0.   0. 217. 120.  69.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 40. 127. 102.   0.   0. 224.   0. 102.   0.   0.   0. 165. 148. 255.
   44.   0.   0.  50.  51.   0.   0.   0.   0.   0. 102.   0. 135.   0.
    0.   0.   0. 107.   0.   0.   0.  41.]
 [ 18.  45.  77.   0. 106. 130.  31.   0.   0.   0.   0.  95.  40.   0.
  121.  94. 236.  17.   0.  44.  45.   0.  27.   0.   0.  59.   0.   0.
    0.   0.   0.   0.  43.  10.  83.  30.]
 [  0.   0.   0. 137.  78.   0.   0. 142.   0.   0.   0.   0.   0.   0.
    0. 122.  61.   0.   0.   0.   0.   0.   0.   0.  81.  95.  18.  39.
    0.   0.   0.   0.  27. 137. 573. 204.]
 [128.   0.  55. 139.  57. 137.  67.  31. 207. 118. 255. 116. 235. 294.
  254. 110.   0. 118. 103. 171.  55.   0.   0.   0.   0.   0.  47.  45.
    0.   0.  38.  82.  66.   0.  20.  14.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [134.  49.  93.  16.   0. 154.   0. 153.   0.  34.   0.   0. 349.  72.
    0.  34.  37.   0.  60.   0.  22.   0. 244.   0.   0.   0.   0.  34.
  201.  42.  23.  47.  28.   0.   0.   0.]
 [  0.   0.  42. 121. 270.   0.   0.   0. 182. 456. 521. 263.  78.  43.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   19.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 231. 226.  55.   0.   0.   0.  21.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 200.   0.   0.   0.  18.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [216. 164.   0.   0.   0.   0.   0.   0.  98. 287.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  19.  88.   0.  24.   0.   0.   0.   0.   0. 166.
   42.  30.  48.  26.   0. 111.  68.  58.   0.   0.   0.  17.  54.   0.
    0.   0.   0.   0.   0.  87.  57. 133.]
 [  0.  17.   0.   0.   0.   0.   0.   0.   0.   0. 143.   0.   0. 327.
  100.   0.   0.   0.   0.   0.   0.  62.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  89. 165.   0.   0. 124.]
 [  0.   0.   0.  32.  95.  57.  61.  83.   0.   0.   0.   0.  93.  95.
   56.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  95.  88.   0.  55.  66.  82.]
 [178.   0.   0.  93.   0.   0.   0.   0.   0.   0.   0.   0.  85.   0.
   49.  56. 184.  49. 142.  24.   0.   0.   0.  39.  24.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 73.  21. 105. 111. 220. 350. 176.   0.   0.  28. 112. 125.   0.   0.
   35.  57. 111. 190.   0. 113.   0.  22.   0.   0.  71.  89.  73. 114.
  203. 104.  90.  56. 108.  34.   0.  21.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  93.  31.   0.   0.   0.   0.
    0.  75. 198. 102. 111.   0.   0.   0.]
 [188.  89.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 272.  27.   0.   0. 106. 202. 388. 199. 282.   0.   0.   0.
    0.   0.  30.  48.   0. 115.   0.  29.]
 [108.  25.   0.   0.  24.  22.  18.   0.  78.  27.   0.   0.   0.   0.
    0.  15.  35.   0.  13.  40. 174.  75. 219. 118.   0.   0.  67.  36.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  73.  17.   0.   0.   0.   0.   0.   0.  94. 166. 486. 326. 531.
  539. 125.   0.   0.   0. 175.  37.  28.   0.   0.   0.   0.  21.   0.
    0.   0. 166. 522. 475. 513. 513. 454.]
 [  0.   0.   0.   0.   0.  24.   0. 100.  18.   0.   0.   0.   0.   0.
    0.   0.  22.   0.   0.   0.   0.   0.   0.  97.  41.  19.  44.   0.
    0.   0.   0.   0.   0.  91.  29.   0.]
 [  0.  19.  18.   0.   0.  18.  12.  42.  13.  90.   0.   0. 104. 135.
   19.  45.  34.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  31.
    0.   0.   0.   0.   0.   0.  61.   0.]
 [  0.   0.   0.  99.  61. 115.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  55. 554. 676.]
 [  0.  77.  60.   0.   0.  86.  37.  39.  42.  18.   0.   0. 136.  20.
    0.   0.  63.  45.  95.  43.   0.  23.  13.  35.   0. 167.  94.  68.
   77.  18. 179. 165. 159. 136.  32.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 358.  43.   0. 484. 225.  26. 178.   0.   0.   0.
  277. 644. 125.   0.   0.  19.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 103. 276.  15. 395. 396. 184.
   41.  45.   0.  52.   0.   0.   0. 104.   0.   0.  44. 105. 193.   0.
    0.   0.   0.   0. 254.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  52. 262.  58.  59.  63.  66.   0.  55.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  59.  33. 181.
  445. 451. 488.  31.  41.   0.   0.   0.]
 [288.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  101.   0. 531. 211.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  77.   0.   0.   0.  35.  20.  51.   0.   0.  15. 171.  37.   0.
    0.  53.   0.   0.   0.  21.   0.  19.   0.   0.   0.  22.   0. 167.
   54.   0.  24.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  25.   0.  35.  73.  62.
   22.  24.  42.  51. 138.   0.  51. 113.  42.  71.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  69.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  41.   0.   0.   0.   0.
    0.   0.  51. 100.  30.   0.   0.   0.   0.   0.  77.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  52.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  65.  63.   0.   0.   0.  60.   0. 101.  29.   0.
    0.  34.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  48.   0.
   63.   0.   0.   0.   0.   0.   0.   0.]
 [ 22. 240.  21.  34.   0. 247.   0. 197.   0.  88.   0. 185.  42.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 344.  84.  61.
  153. 144.   0.  76.  48.   0.  32.  24.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  34.   0.
    0.   0. 265. 458.  34.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 109.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 112.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  30. 122.  39.  96. 245.   0.   0.
    0.  62.  65.  80.   0.   0.   0. 135.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 129. 388. 448. 521.
  580.  49. 209. 196. 426.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  18.   0.   0.   0.  33.  41.   0.   0.   0.   0.   0.   0.   0.
  170.   0.   0.  19.   0.   0.   0.  20.   0.   0.   0. 104.   0.  28.
  161.   0.   0.   0.   0.   0.   0.  47.]
 [ 72.   0.   0.   0.   0.   0.   0.   0.   0.  21.  45.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  69.   0.  23.  22.]
 [  0.   0. 224. 446.  66.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  23.   0. 448. 210.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 194.]
 [ 38.  41.   0.   0.   0.   0.   0.  31.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  62.  95.  56.   0.   0.   0.   0.   0.   0.   0.   0.
   56. 201.   0.   0. 134.  51.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  97.   0. 337.  35.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 115. 207.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 247.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  61. 134.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 110. 158.  37.  52.  65.   0.   0.  30.  20.   0.
    0.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 337. 106.  47. 124. 130. 218. 164.
    0.   0.   0.   0.   0.   0.   0.   0.  16.   0.   0.   0.   0.   0.
    0.   0.  74. 239.   0.  58.   0. 127.]
 [ 25.   0.   0.  96.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  49.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   18.   0.   0.   0.   0.   0.   0.   0.]
 [161.   0.   0.   0.   0.  98.   0.   0.  33. 117. 284.   0.   0.   0.
    0. 205. 125.   0.   0.   0.   0.   0.   0.  41.  84. 225.  56.  36.
    0.   0.  72.  25.   0.   0.   0.  88.]
 [ 30.  26.  99.  88.  19.   0.   0.   0. 106.   0.   0.   0.   0.   0.
    0.   0. 114.   0.   0.   0.  94.   0.   0.   0. 110. 332.   0.   0.
    0.   0.   0.  98.   0.   0. 168.  92.]
 [223.   0.   0.   0. 251. 555. 407. 386. 205.   0.   0.   0.   0.   0.
    0.   0.   0.  25.   0.   0.   0.   0.   0.  18. 328. 596. 461.   0.
    0.  57.  26.  26.   0.   0.   0.   0.]
 [ 24.   0.   0.   0. 167.  34.  18. 112.  83.  65.   0.   0.   0. 263.
   37.   0.   0.   0.   0.   0.  18. 144. 290.   0.   0.   0.   0.  97.
  227. 242. 229. 130.   0. 127.  29.  72.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  33.   0.   0.   0.   0.   0.   0.   0.   0.  36.  16.  33.
   23.   0.   0.   0.   0.   0. 131. 199.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 191.  49.  26.
  168.   0.   0. 250. 234.  75.  22.  34. 198.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  20. 133.   0.   0.   0. 280. 358. 557. 335.  86.  47.   0.
    0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  37.
    0.  37.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  82.  96.  26.   0.  71.   0.   0.  99. 107.  64. 219.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.  43.   0.   0.   0.   0.  59.   0.   0.   0.   0.
    0.   0.   0.   0.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 167.  27.   0.]
 [  0.   0.   0.   0.  18.  67.   0. 289. 235.  79.  19.  23. 284. 646.
  631. 592. 593. 254. 621. 586. 706. 433.  26.   0.  51.   0.   0.  44.
    0.  24.   0.  31.  21.   0.   0.   0.]
 [  0. 357. 219.   0.   0.   0.   0.   0.   0.   0.  77.   0.   0.   0.
    0.   0.  63.  60.   0.   0.   0.   0.   0.  67. 123. 165.  34. 315.
  550. 482. 477. 381. 517. 452. 483.  40.]
 [340.  40.  29.  44. 145.  76.  40.  75.  91. 219.  90.  99. 158.   0.
   36.  42.  54.   0. 208. 181.  18.  18. 105.  53.  35.  22.  77.  42.
    0.  18.   0.   0. 173.   4.  22.  22.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 168. 289.  41.   0.   0.   0.
    0. 317.  29. 191. 281. 242. 575. 516. 313.  84.   0.   0.   0.   0.
    0.   0.   0.   0. 129.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  22.  16.   0.   0.   0.
    0.   0.  78. 264.   0.  47. 216.  50. 351.  73.   0.  71.   0.   0.
   57.  52.   0.  32.  22.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 185.  93. 420.
  349. 386.  69.  97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 130. 164. 357.  54.   0.   0.]
 [  0. 137.  67. 285. 149.   0.  29.  42.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  59. 332.   0.  15.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [315. 410.   0.   0.   0.  58.  25.  38.  17.  37.   0.   0.   0.   0.
    0.  22.  21.  46. 270. 226.  46. 128.  66.  50.  36. 409. 357. 291.
  360.  32.   0.   0.  70.   0.  12.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 138.  21.  61.   0.   0.   0.  31.   0.  93.   0.
    0.   0.  34.   0.  65.  32. 161.  30.]
 [  0.   0.   0.  42.  60.  71. 166. 141.  72.  98.  40. 346.  66.  39.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  22.  94.  14.   0.  62.  63.  88.]
 [  0. 338. 521. 387.  30.   0. 155. 445.  33.  34.   0.   0. 403. 393.
    0.   0.   0.   0.   0.   0.  19.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  18.]
 [  0.   0.   0.  32.   0.   0.   0.   0. 162. 110.   0.   0.   0.   0.
    0.   0. 154.   0. 163.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  29.  47.   0.   0.   0.]
 [466. 114. 455. 156.   0.   0.   0.   0.   0.   0.  96.  27.  31. 128.
    0.  63. 113.   3.   0.  23.  94.  87.   0.   0.   0.   0.   0.   0.
  111. 128.  20.  14.   0.   0.   0. 152.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 220. 295. 457.]
 [  0.  94. 104.  20.  23.  27.   0.   0.   0.   0.   0.   0.   0.  19.
    0.  21.  65.  30.  77.  15.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 131.  15.   0.   0.   0.   0. 117.   0.  25.   0.   0.   0.
    0.   0.   0.   0.   0.  95. 233. 409. 154.  23.  25.   0.   0.   0.
    0.   0.   0.   0.  73. 540.  28.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  66.  42.  48.
   44.   0.  19.  80.   0.   0.   0.   0.  22.  50.   0.   0.   0.  31.
    0.   0.   0.   0.   0.   0. 103.   0.]
 [ 73.  75.  22.   0.   0. 129.   0.   0. 116.   0.  63.   0.   0.   0.
    0.   0.   0.  40.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  46.   0.   0.   0.  25.  62. 148.]
 [  0. 106.   0.   0.   0.  19. 127. 192.  97. 239. 146.  98. 135. 151.
  222.  43.  28. 114.  96. 149. 112.  96. 145.  76.  70.  93. 203.  42.
   65. 110.  95.  92. 265.   5. 330. 133.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[319.  69.  82. 115.  77. 146. 189.  94.  47. 119. 240.  39. 141. 161.
   31.   0.  52.  73.  63.   0.   0.   0.   0.   0.   0.   0.  88.   0.
    0.   0.   0.  12.  54.   0.   0.   0.]
 [ 88.  45.  18.   0.   0.  62.  43. 123.  39.  86.   0.  35.   0.   0.
   20.  25.  23.   0.  19.  47.   0.   0.   0.  29.   0.  20.  19.  50.
   40.   5.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 370. 773. 715.]
 [108. 135.  94. 184.  73. 340. 226.  61.   0.   0.   0.   0.   0.   0.
    0. 155.  83. 290. 258. 156. 174.  84.  60.   0. 264.  35.  64.  70.
    0.   0.   0.   0.  72.   0.   0.  20.]
 [160. 150.   0. 145.  39.   0. 218. 148.   0.   0. 141. 362. 505. 108.
    0.   0.   0.  33.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  25. 366. 215.  54.  15.   0.  38.]
 [  0. 117. 134. 349. 138. 378. 383.   0.   0.   0.   0.   0.   0.   0.
    0.  48.  64. 206. 447. 576. 592. 574. 357. 585. 273. 287. 155.   0.
    0.   0.   0.   0.   0.   0.   0.  15.]
 [  0.   0.   0.   0.   0.   0.   0.  41.   0.   0.   0.   0.   0.  18.
    0.   0.   0.  32.   0.   0.   0.   0.   0.  42.  65.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 103.]
 [  0.   0.   0.  27.  47.   0.   0.   0.   0. 183.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  28.  79. 256.   0.   0.   0.   0.
   17.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 144.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  71.   0.  92. 108.  68.
   63.   0.   0.   0.   0.   0.  40.   0.]
 [  0.  88.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  22.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 26.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.
    0.  16. 128.   0.   0.   0.   0.   0.   0. 113.   0.   0.   0.   0.
    0.  37.  16. 116. 161.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 154. 359.   0.   0.
   98.  42.  70. 149. 109.   0.   0.   0. 157. 335. 249. 149. 216.  18.
    0.  63. 223. 162. 195. 205. 227. 180.]
 [  0.  51.  49.  47.   0. 101.  45.   0.   0.  54.  43.  37.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 170. 165.   0.   0.   0.   0.   0.
    0.   0.   0.  19.   0.   0.  97.  42.]
 [  0.  20.   0.   0.   0.   0.   0.   0.  33. 104.   0.  73.  96.  67.
  139. 148.  84.  69.  87.  20.  22.  50.  46. 103.  65.  93.  87. 184.
  201. 279. 366. 229.  19.  28.  61.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  31.  57. 245.  40.  28.]
 [  0.   0. 245.   0. 193.   0.   0.   0.   0.   0. 145. 166.   0.   0.
    0.  56.   0.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 368.   0. 281. 314.   0.   0. 101.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 381. 537.   0.]
 [  0.  84.  71.  44.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  58.   0.   0. 120.  18.   0.   0.   0.  22.   0.   0.   0.   0.
    0.  33.  56.   0.   0.   0.   0.   0.]
 [407.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  29. 175.
    0.   0.  74.  84.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[170.   0.   0.   0. 129.  16.   0.   0.  86.  63.   0.   0.   0.   0.
    0.   0.  28.  21.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  40.  50.   0.   0.   0.  16.]
 [  0.   0.   0.   0.   0.   0.   0. 101.   0.  90. 110.   0.   0.   0.
    0.  19.  28.  13.  12.  14.   0.   0. 135.   0.   0.   0.   0.   0.
    0.  34.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  17. 109. 194.  21.   0.   0.   0.   0.   0.   0.   0.  76.
  129.   0.   0.   0.   0.  37.   0.   0.   0.   0.   0.   0.  91.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 97. 120.   0.   0.   0. 120.   0.  24.   0.   0.   0.   0.   0.  49.
   72. 212.   0.  81.   0.   0.   0.   0.   0.   0.   0.   0.   0.  88.
  130.  27.  18.  27. 150.  65.   0.  52.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  12.   0.
  117. 389.   0.   0.   0.   0.   0.   0.   0.   0.  43.   0.   0.   0.
    0.   0.  38.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 140. 229. 394. 314.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  19.]
 [  0.   0. 474. 227.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   43.  22.   0.  31.   0.   0.   0. 345. 473. 529. 524. 514.  69.   0.
  487. 487. 532. 438.  33.  24.   0.   0.]
 [ 51.  57. 153.  51.  35.   0.   0.  54.  24. 220.  86.  86.  42.  26.
    0.  33.  62.  38. 133.  25.   0.   0.  62.  36. 105. 202. 113.  40.
    0.   0.   0.   0.  78.   0.   0.  91.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 191.  60.   0.  19.  66.]
 [  0.  20.  20.   0.   0.  33.  56.  48.  65.  32.   0.   0.   0.  57.
    0.  39.   0.   0.   0.   0.  26.   0.   0.   0.   0. 120.  78. 125.
   40. 125.  44.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 143.  33.   0.   0.   0.   0.   0. 556. 136.   0.   0.
   42. 269.   6.   0. 445. 228. 226. 335.]
 [332.  86.   0.  39.  69.   0.   0.   0.   0.   0.   0.   0.  25.   0.
   80. 217.  56. 316. 127.   0.  39.   0.   0.   0.   0.   0. 108. 139.
    0.  48.   0. 225.   0.   0.   0.  79.]
 [  0. 211. 423. 181.   0.   0.   0.  26. 224. 234.  59.   0.   0.   0.
    0.  12. 222.   0. 127. 121. 385. 107.   0.   0.   0.   0. 192.   0.
    0.   0.   0.   0.  16. 353. 587. 568.]
 [219.   0. 125. 449.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  46.  62.   0.   0.
   18.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  82.  62.  95.   0. 100.   0.   0.   0.   0.   0.   0. 163.  17.
    0.  87.  67.   0.  22.   0.  30.  54.   0.   0.  20.   0.   0.  27.
   19.   0.  82. 193. 165. 202.   0.  22.]
 [ 85.   0.   0.  56.   0.   0.   0. 212.  29.   0. 437. 138.  18.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 303. 248.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 167.   0.   0.   0.  50. 108.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  71.  22.  88.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  75. 510. 284.
    0.   0.   0.   0.   0.   0.   0.  69.  35.   0.   0.   0.   0.   0.
   20. 314. 578. 313.  21.  13.   0.   0.]
 [  0.   0.  12.  36.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.  55.   0.   0.  79.  19.  58.  52.   0.   0.   0.  84. 106.
  101.  88.  36.  62. 136. 317. 563. 365. 413. 441. 198.  54.  85.   0.
   46.  22.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  54.  19.  34.   0.
    0.   0.   0. 352.  48.   0.  61. 138. 241. 109. 149.  71.  59. 109.
    0.   0.   0.   0.   0.   0.  62.  36.]
 [199.   0.  22. 219. 535.  23.  43.  41.   0.   0.  23.   0.   0.   0.
    0.  64.   0.   0.   0.   0.  27.  63.   0.   0.   0.   0.  65.  22.
   22. 450. 473.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 333. 157.  97. 579. 425.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  18.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 287. 483.  37.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  18. 108. 181.   0. 229.
   44.   0.   0. 172.  61.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  126. 240. 152.   0.  47.   0.   0.   0.]
 [  0.  62. 111. 227. 545.  41.   0. 295. 260. 224. 220.  16. 139.  65.
   73.   0. 107. 116. 158.  97. 176. 216. 243. 232. 116. 255. 248. 173.
  220. 302. 118.  22. 165. 191. 177.  53.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 112.]
 [  0.   0.   0.   0.   0.   0. 244. 247.   0.   0. 161.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 223.  50.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  37.  19.   0.   0.]
 [  0.   0.   0.  22.  62.   0.   0.   0.   0.   0.  60.   0.   0.   0.
  162.   0.   0.   0. 298.  89.  57.  47.  40.   0.   0.   0.   0. 115.
  105. 106.   0.   0.   0.  99. 174.  32.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 102.  92.   0.   0.   0.   0.  24. 211. 146.  72.  81.  29.   0.
   30.  21.  20.   0.   0.   0.   0.   0.]
 [  0.  90. 144. 552. 350. 172. 206. 665. 709. 642. 623. 652. 443. 632.
  601. 648. 453. 200. 186. 227. 463. 394.   0. 134. 113.  45.   0.   0.
    0.   0.   0.   0.   0. 204. 240.  49.]
 [  0.   0.  23. 141.   0.   0.   0.   0.   0.   0. 241.  20.  64.  35.
   97.   0.   0. 130.  36.  32.  26.   0.   0.   0.  39.  70.  28. 100.
    0.   0.  37.  37.   0.   0.  32.   0.]
 [ 33.  33.  29.   0.  84.   0.   0.  18.   0.  23.   0.   0.  69.   0.
    0.  33.  53.  20.   0.   0.  47.  48.  18.  31.   5.  23.  28.  42.
   21.   0.   0.  21.  60.  22.   0.  18.]
 [202. 263.   0.   0.   0.   0.   0.   0.   0. 136. 568. 574. 120.   0.
    0.   0.   0. 193.   0.   0. 106. 124.   0.   0. 383. 155.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  86.   0.   0.   0.  19.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.  77. 172.   0.  19.  71.
  129.  27.   0.   0.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 239. 231. 248. 170.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  31.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  96. 121. 602. 785. 798. 793. 798. 797. 814.
  752.  60.  74.   0.  90. 220.   0.  18.]
 [210. 182.   0. 138.  55. 127.   0.  21.  20. 109.   0.  29.  91. 149.
   12. 108.   0.   0.  29.  93. 104. 128. 106.  91.  90.  28.  73.   0.
    0.  78.   0.   0.   0.   0.   0.   0.]
 [  0.  63. 213. 338. 321.  46. 130.  96.  31.  44.  19.  84.  37.  22.
   20.  86.  40.  64.  43.  46.   0.  20.   0. 106. 277.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20.   0.   0. 109.  40.   0.   0.  97.  26.   0.   0.   0.   0.
    0.   0. 148. 355.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.
   18.  37. 136.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  37.   2.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  22.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  44.   0.   0.   0.   0.   0.   0.   0.  20. 280.
  196. 192.  79.   0.   0.   0.   0.  19.]
 [  0. 111.  19.   0.   0.   0.   0.   0.   0. 130.  61.   0.   0.  50.
   98.  84.   0.   0.   0.  57.  31.   0.   0.  35.  30. 113. 100.  85.
    0. 524. 566. 536. 555. 550. 547. 363.]
 [  0.   0.   0.   0.  39.  28.   0.  69.   0. 109.   0.   0.   0.   0.
    0.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  44.]
 [  0.  51.  85. 313.  19.   0.  60.  28.   0.   0.   0.  56. 156.  54.
  131.   0.   0.   0.   0.   0.   0.   0.   0. 105.  74.  42.  13.  90.
   44. 141.   0.  19.  90.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 164.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  45.]
 [ 20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  28.  45.  27.   0.   0.   0.   0.   0.   0.   0.  23.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  48.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 174.  27.   0.   0.   0.
    0.   0. 316.  34. 340. 359. 216. 266.]
 [  0.   0.  47.  20.  24.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  47.   0.   0.   0.   0.  22.]
 [198.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 220.
   77.  45. 137.   0.   0.   0.  21.  21.   0.   0. 134.  82.   0.  61.
   97.   0.   0.   0. 122. 207. 157. 117.]
 [  0.  54.   0.   0. 101. 240. 178.   0.   0.  87. 257.   0. 144.  41.
    0.  62. 180. 222. 152.   0.   0.   0.   0.  79.  69. 122.  98. 184.
  230. 104.  26.   0.  34.   0.  31.   0.]
 [100. 510. 117. 323.  39. 264.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  39.  92. 218.   0.   0.  18. 119.
   34.   0.   0.   0.   0.   0.   0.  40.]
 [ 56.   0.  22.  22.   0.   0.   0.   0.  21.   0.  26.   0.  21.   0.
    0.   0.   0.  99.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  20.   0.   0. 127.  40.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[413. 536. 443. 532. 523. 444. 551. 548. 551. 535.  36.  33.   4.   0.
    0.   0.   0.   0.  19.   2.  86.  33.   0.  48.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  71.   0.  25.   0.   0.   0.   0.  97.  78.   0.   0.   0.   0.
    0.   0.   0.   0. 127.   0.   0.   0.   0.  38. 104. 145.  46.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [206. 334. 115.  82. 107. 257.  62.   0.   0.   0.   0.   0.   0.   0.
   74.  21.  53.   0.   0.   0.   0.  55.   0.   0.   0.   0.  37.   0.
    0.   0.   0.   0.   0.  46.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  22. 136. 125.  84.
    0.   0.  39.   0. 177. 159. 127.  54.   0.   0.  54.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  20.   0.]
 [ 13.   0.   0.   0.  44.  28.  73.  57.  18.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  76.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  20.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  45.   0.   0.
    0.  44.   0.   0.  45. 151.  39.   0.   0.   0.   0.   0.   0.   0.
  185. 129.   0.   0.  20.   0.   0.   0.]
 [ 16.   0.   0.   0.   0.   0.   0.  70.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 100.  49.   0. 108.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 104.   0.]
 [  0.   0.  24.   0.   0.   0.   0.  33.  57.   0.  25.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  57.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 95. 309. 541. 534. 526. 143.   0.  69.   0.   0.  57.   0.  32.   0.
   21. 114. 167.   0.  42.  93.  37.  83.  69. 118.  71.  56. 139.  89.
  180.  64.  45.  23.  87.  66.   0.   0.]
 [  0.   0.   0.  45.  45.   0.  18.   0.  59. 243.   0.  71.  76.  98.
    0.   0.   0.   0.  52.   0.   0.   0.   0.   0.  65.  70. 117.  20.
    0.  57.   0. 321. 298. 275.  30.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 117. 650. 209.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  24. 553. 445. 257. 575.  59.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   21.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 118.   0.  25.  58.   0.   0.  43.   0.  22.  18.   0.   0.   0.
    0.   0.   0.   0.  37.  62.   0.  58.]
 [  0.   0.   0. 100. 261.  96.  18.   0.   0.   0.   0.  75.   0.  99.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 219. 218.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  47.   0. 122.  39.   0.   0.   0.  37. 226.   0.   0.   0.   0.
    0.   0. 154.   0.  51.   0.   0.  76.]
 [112.   0. 234. 211.  38.   0.   0.  44.   0.  23.  22.   0.   0. 103.
    0.   0.   0.  82. 197.   0.   0.   0.   0.  20.  41.   0.   0. 138.
   32. 273. 349. 101. 115.  79. 120. 246.]
 [  0.   0. 157.   0.   0.   0.   0.   0.   0.   0.   0.   0. 452. 422.
  376. 571. 670. 638. 613. 550. 301. 224. 144. 313. 426. 531.  72.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  25.  28.   0.   0.   0.   0.
    0.   0.   0.   0. 257.  32.  31.   0.   0.   0.  31.  39.  43.  19.
  572. 178.  76.   0.   0.   0.  20.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 34.  11.   0.  44.  78.   0.   0.   0.   0. 134.  30.   0.  29.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  61.  74.
  140.  65.   0.   0. 147.  21.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.  77.  46.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 106.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   21. 205. 165.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  19. 306. 315.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  13.   0.   0.]
 [ 42.   0.  30.  42.   0.  26.  22.   0.   0.   0.   0.   0.  20.  64.
    0.   0.   0.   0.   0.   0.   0.   0.  21.  26.   0.  26.   0.   0.
    0.   0.   0.   0.   0. 113.  20.   0.]
 [ 95.  91.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  30. 119.   0.  20.  25.   0.   0.
    0.   0.   0.   0.  19. 313.  60. 394.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  93.  36.
  115.  25. 419.  43.   0.  66.  30.   0.  97.  61. 140.   0.  41. 284.
  169.  67. 134.  20. 372. 292. 187.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 41.  33.   0.   0.   0.   0.   0.  55.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0. 259.  84. 103.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 174.   0.  32.
  387.   0.   0.   0. 214. 126.  34.   0. 160.  49. 406. 551. 553. 555.
  565. 576. 548. 599. 357.  72.   0.  34.]
 [  0.   0.   0.  19.   0.   0.   0.   0.  40.   0.   0.   0.   0.  23.
    0.   0.   0.   0.   0.   0.   0.  28.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 99.  19.  45.  83.  61.  92.  36.   0.   0.   0.   0.  42. 104. 286.
  609. 399.   0.   0.   0.   0.   0. 395. 546.  39.  37.   0.   0.  79.
   27.  84.  34.  34.   0.  84.  14.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  81.  36. 154.  45.  60.  93. 116.
   41.  51.  36.  60.  21.  40. 145.  50. 218.   0.  18.  18.   0.   0.
    0.  36. 183.  91. 309. 279.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  58.   0.   0.   0.   0.   0.   0.
   64.   0.  84.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 110. 317.   0.  16. 199. 159.  40.   0.   0.   0.  42.  73.
   19.   0.  42.   0.  53. 115.   0.   0.   0.  59.   0.   0.  50.   0.
    0.   0.   0.  47. 155.  21. 193. 117.]
 [  0.   0.   0.   0.   0.   0. 180.  18.  22.  22.   0.  24.   0.  67.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   35.  51. 272.  23.   0.   0.   0.   0.]
 [  0.   0.   0.  53.  42.  68.  61.  57.   0.   0.   0.   0.  24.   0.
   67. 168.  83.   0.  87.   0.   0.   0.   0.  68.  40.   0.   0.   0.
    0.  59. 162.  76.   0.   0.   0.   0.]
 [ 41.   0.   0.  31.  81.  48.  32.  73.   0.  19.  73.  33.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  75.   0.   0.   0.   0.   0.  50.
    0.  42.   0.  56.  25.  20.   0. 117.]
 [  0.   0.   0.   0.  41.  85.   0.   0.   0.   0.  75.   0.   0.   0.
    0.   0.  75.   0.   0.   0.   0.   0.   0.   0.  39.   0.   0.   0.
    0.   0.   0.   0.   0. 214. 310. 202.]
 [ 75.  32.   0.  55.   0.   0.  39.  24.   0.   0.   0.   0.   0. 109.
   54.  52.   0.  37.  39.   0.  56.  24.   0.   0.   0.   0.  54.  32.
   19.  47.   0.   0.  52.   0.   0.  23.]
 [  0.   0.  36.  13.   0.   0.   0.   0.   0.   0.  43.  77. 706. 809.
  806. 790. 789. 779. 593. 771. 802. 422.   0. 145. 110. 287.  60.  48.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.  63. 110.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 100.   0.   0.]
 [  0. 108.  30.   0.   0.   0.   0. 114.   0.   0.   0.   0.  41.  84.
  148.   0.  26.  20.  30.   0.  41.  24.  20.  18.   0.   0.   0.   0.
   88. 107.  25.   0.  37.  18.  39.   0.]
 [  0.   0.   0.  23.   0.   0.  24.   0.   0.   0.  74.  89.   0.  23.
   40.  18.  14.   0.   0.  84. 126.   0.  22.  98.  11.  90. 112.  70.
    0.   0.   0.   0.  84.   0.  54.  64.]
 [  0.  91.   0.   0.   0.   0.   0.   0.   0.   0.   0. 124.  19.   0.
    0.   0.   0.   0.   0. 110.   0.   0.   0.   0.   0.  41.  46.  86.
    0.   0.   0.   0.  76.   0.   0.   0.]
 [  0.   0.   0.  49.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   24.   0.  74.  83.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  18.  45.   0.]
 [  0.   0.   0.   0.  21.  25.   0.  74.  28.  22.   0.   0.   0.  22.
   43.  21. 107. 112.   0. 120.  21.   0.  21.  22.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  22.]
 [  0.   0.   0.   0.  46. 101.   0.   0.   0.   0.   0.   0.   0.  26.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 129.  99.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [115. 220.  82. 206.  99.  88.   0.   0.   0. 148.  37.  56. 132.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  80.   0.   0.   0.   0.   0.
    0.  21. 137.  77.   0.   0.   0.   0.]
 [105.  67. 283. 153.  71.  20.  58. 298.  93. 439. 297.   0.   0.   0.
    0.   0.   0.   0.   0. 448. 464.   0.   0. 563. 589. 496.   0.   0.
    0.   0.   0.   0.  26.   4.   0.   0.]
 [  0.   0.   0.  24.   0.   0.  51.   0.   0.   0. 109. 207. 184.   0.
   33.   0.   0. 143.   0.   0.   0.   0.   0.   0.   0.   0.   0.  17.
  120. 108. 239.   0.   0.   0.   0.  25.]
 [  0. 540.  41.   0. 537. 101.   0.  22.   0.   0.   0.   0.  19. 416.
  259. 111.  50.   0.   0.   0.   0.   0.   0.  76.  30.  18.  18.   0.
    0.   0.  21.   0.   0.   0.   0. 236.]
 [  0.   0.   0.   0.   0.  42.  23. 162. 108.   0.   0.   0.  95.  74.
   60.   0.   0. 182.   0.   0.   0.   0.   0.   0.  18.   0.  39. 178.
   85.   0.  19. 171. 153.   0.   0.   0.]
 [  0.   0.   0.  22. 106.  27.   0.   0.   0.   0. 130.  95. 132.  76.
    0.   0.  19.   0.   0.  39.   0.   0. 109.  49.  76.   0.   0.  26.
   68.   0.   0.   0.   0.   0.   0.   0.]
 [120.  18.  30.  34.  35.   0.   0.   0.   0.   0.   0.  20.  40.   0.
    0.   0.   0.   0.   0.  39.  18.   0.   0.   0.  24.   0.   0.   0.
    0.  42.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  47.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 139.]
 [ 15.   0. 183.   0.   0. 130.   0.   0.   0.  53.   0.   0. 127. 230.
  135. 121.  28.  88.  59.   0. 134. 171.  57. 140.   0.   0.   0. 139.
   15. 247.  53. 212.  20.   0.  83.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  33.   0.   0.   0.  63.  20.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[191.   0.  20.  46.   0.   0. 179. 124.  29. 280. 184.  95.   0.   0.
    0.  45. 175.   0.   0.   0.   0.   0.   0.   0. 161. 175.  92.  27.
    0.   0.   0. 152.   0.  41.   0. 121.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 141.   0.  18.   0.
    0.   0.   0.   0.  91. 386. 176.   0.   0.   0.   0.   0.   0.  36.
  385.  53. 155.  84. 479. 225.   0.   0.]
 [718. 793. 793. 798. 795. 779. 820. 799. 541.  75.  79. 214. 104.   0.
  373. 336.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 12.   0.   0.   0.  81.  63.   0.   0.   0.  37.  42.   0.  50.   0.
    0.  54.  61.   0.  21.   0.   0.   0.   0.   0.   0.  32.   0.  14.
    0.   0.   0.   0.   0.  89.  30.  55.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 195.   0.   0.  18.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 31.  37. 117.  37.  65.  31.   0.   0.   0.   0.   0.  35.   0.   0.
   58.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  78.  96.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  65.  80.  69. 132.  49.   0.  87.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  63.   0.
    0. 206. 217.   0.   0.   0.   0.  40.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  26.   0.   0.   0.   0.
    0.   0.   0.  62.  34.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  20.   0.   0.   0.   0.   0.]
 [  0.  82. 145.  83. 106.   0.   0.   0.   0. 216.  29.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  73.  74. 116.   0. 141.
   20. 306.   0.  83. 201. 201. 171. 252.]
 [ 80.  38.   0.  35.  13.   0.  21.   0.   0.   0.  49. 111.   0.   0.
   68.  35.   0.  38.  45.   0.   0.  37.   0.  29.   0.  37.   0.   0.
    0.   0.   0. 160.   0.  47. 113. 178.]
 [  0.   0.   0.   0.   0.   0.  39.   0.  65.   0.  65.  20.   0.  18.
   26.   0.   0.   0.   0.   0.  53.  36.   0.   0.   0.  43.  23.   7.
    0.   0.   0.  47.   0.   0.   0.  28.]
 [  0.  39.  16.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  51.   0.  27.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  24.   0.   0.]
 [  0.  46.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  64.  77.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  19.  48.   0.   0.]
 [  0.   0.   0.   0.  44. 442.   0.   0. 190.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 159.  66.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  18.   0.   0.]
 [  0. 156.  43.   0.   0.   0.   0.   0.   0.  33.   0.   0.   0.   0.
   61.  44.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  72.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  30.  23.   0.   0.   0.   0.  46.   0.  49.  19.  18.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  23.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  70.]
 [  0.   0.  25.  13.  81.   0.   0. 243. 105. 200. 383.  50.   0.   0.
   91. 278.  82.   0. 243. 259. 309. 512. 309.   0.   0.   0.   0.   0.
    0.  18. 435. 465.  47. 199.   0.   0.]
 [ 41.  14.  71.  61.  15.   0.   0.  35. 106. 221. 626. 589. 588.  10.
    0.   0. 505. 290.   0.   0.   0.   0.  50.   0. 298.  64.   0.   0.
    0.   0.   0.   0.  95.   0. 101.  56.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  34.  51.  19.   0.]
 [ 32.   0.   0.   0. 304. 486. 510. 185.   0.   0.   0.   0.  30.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  18.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.  92.  45.  25.  38.   0.   0.  29.   0.   0.   0.  77.  54.
   16.  22.   0.   0.  81. 297.  20.   0. 133.  29. 185.  20. 163.  75.
   22. 125. 168.  35.   0.  62.  61. 108.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  29.  21.   0.
   41.  66.   0. 122.   0.   0.  34.   0. 160. 139.   0.   0.   0.   0.
    0.   0.   0. 102.   0.   0.   0.   0.]
 [ 74.   0.   0.   0.   0.   0.   0.   0.  23.   0.   0.  37.  44.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 115.  95.   0.  62.  25.   0.  35.]
 [  0.   0.   0.   0.   0.   0.  32.   0.   0.   0.   0.   0.   0.   0.
    0.  87. 123.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  18.   0.   0.   0. 354.   0.   0.
   17.   0.   0.   0.   0.   0.   0.   0.   0.  18.   0.   0.   0.   0.
   18.   0.  49.  13.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  23.   0.   0.   0.   0.  41. 217. 237. 375.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  29.  26. 425. 199.   0.   0.]
 [173.   0.   0.   0.  21.  20.   0.   0.  65. 210.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  42.   0.  24.   0.   0.   0.   0.   0.   0.
    0.  86. 112.   0.   0. 146. 157.   0.]
 [  0.   0.   0.   0.   0.   0.  28.   0.   0.  72.  34.  42. 120.   0.
    0.   0.   0.  19.  63.   0.  96. 579. 506. 224. 327. 455.  57. 116.
  111.  21.  44.  42. 237. 312. 150. 218.]
 [  0.   0.   0.   0.   0.   0.   0. 162.  24.   0.   0.   0.   0.   0.
   23.  60.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  24.   0.   0.   0.  18.  51.]
 [ 17.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  68.   0.  65.  32.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  79. 208.   0.  85.   0.  29. 183.   0. 353. 144. 151.  75.
  195.  61.   0. 214. 231. 208.  67.  53.   0.  37.  19.   0.  37.   0.
    0.  44.   0.   0.   0.   0.  59. 105.]
 [154.   0.  73. 126.  35.  34.   0.   0.   0.  42.   0.   0.   0.   0.
    0.   0.   0.  21.  41.   0.   0.   0.   0.  49.   0.   0.   0.   0.
    0.   0.  62.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  31. 260. 524. 520. 436. 497. 489. 430. 409.
    0.   0.   0.   0.   0.  68.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  54.  91. 154.   0. 196.]
 [ 20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  55.
    0.   0.  43.   0.   0.   0.   0.  23.   0.   0.   0.   0.  93.  82.
    0.   0.   0.   0.  49.  48.   0.   0.]
 [  0.   0.   0.  78.  58.  29.   0.  19.   0.   0.   0.  18. 115.  61.
    0.   0.   0.  37.   0.   0.   0.   0.  35.   0. 124. 137. 111. 188.
  144.  22. 137.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 150.  31.   0.   0.  28.   0.   0.   0.  19.   0.
    0.   0.  64.   0.   0.   0. 118.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  45.  62.   0.   0.
    0.   0.  22. 188.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 225. 390. 204. 183.
    0.   0.  31.  39.  77.  68. 123.  24.   0.   0.  89.  76.  39. 182.
  546. 557. 403. 518. 427.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 135. 189. 135.  77.
    0.   0.   0.   0.   0.  39.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.  17.   0.  29.   0.   0.   0.   0.   0.   0.
    0.  42. 433. 221.  60.   0.   0.   0.   0.  42.  23.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  36.  45.]
 [159. 189. 165. 179. 238. 266. 281. 302. 160. 227. 235. 254.  53.   0.
    0.   0.   0.   0. 123. 103.   0.   0.   0.   0.   0.   0.   0.   0.
  194.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 194. 372. 247.
   28.   0.   0.   0.   0.   0.   0.   0.   0.  85. 254. 523.  78.  19.
    0.   0.   0. 341.   0.   0.  58.   0.]
 [ 42.  91.   0.   0.  47.  88. 425.  47.   0.   0.  89. 336.   0.  18.
    0. 256.  49. 291. 327.  18.   0.  60.  14.  21. 231.  69.   0.  27.
    0.   0.   0.   0.   0.   0.  61. 201.]
 [133. 183. 179. 235.   0. 230. 148. 106. 154. 220. 101.  52.   0.   0.
   18. 105.   0.  95.  43.  85.   0.  75. 109. 141. 156.   0.   0.   0.
   64.   0.  31.  25.  27.  24.   0.  80.]
 [ 74. 235.   0.   0.   0.  78.   0.   0.   0.  85.  39.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 128.   0.   0.   0. 176.   0.  63.
   72.  38.   0.   0. 183.   0.   0.  89.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 346. 100.  15.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  21.
    0.   0.   0.  19.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 189.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 116. 111.   0.   0.   0.   0.   0.  91. 357.
  556. 523. 346.   0.   0.   0.   0.   0.]
 [133.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  52.   0.
  421. 514. 783. 708. 211. 108. 110. 138. 113.  35.  20.   0.  62.  18.
  158. 105.  85.  28.  34.   0. 123. 128.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 386. 443. 126.   0.   0. 116.  29.   0. 497.  42.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [101.  40.  55.   0.  50.  94.   0.  70. 139. 246. 330. 357. 210.   0.
    0.   0. 231. 368. 446. 475. 105.  25.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  64.  63. 387.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  89.   6. 106.  19.
    0.   0.   0.   0.  72.   0.   0.   0.  23. 566. 611. 614. 612. 117.
    0.   0.   0.   0.   0.   0.   0. 132.]
 [  0.   0.  62.   0.   0.   0.  27.   0.   0.   0.  71. 118. 127. 172.
  174. 121.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   19.  16.   0.   0.   0.   0.  33.   0.]
 [  0.   0.   0. 367.   0.   0. 135.   0.   0.   0.  40.  19.   0.   0.
  247.   0.   0.   0.   0.   0. 110.  19.  64.  18.  30.  52.   0.  37.
   49.   0.  37.  60. 226.  65. 124. 118.]
 [212.   2.   0.   0.   0.   0.   0.   0.   0.  32.   0.  48. 108.   0.
    0. 227. 421.  30.   0.   0.   0.   0.   0.   0.   0.   0.  54.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 207. 136. 113.  20.  20.
   33.   0.  30.   0.   0.  60.  54.   0.]
 [ 14.   0.   0.   0.   0.   0.   0.   0.   0.  47. 121. 128.  28.  59.
    0.   0. 106. 476. 114.   0.  25.   0.  89.   0.  47.   0.  77.  60.
   89.  32.   0.  35. 174.  46.   0. 168.]
 [ 18.  13.   0.   0.   0.   0.   0.  13.  69.  93.  85.  20.  74. 274.
   54.   0.   0.   0.   0. 134. 232. 498. 488. 479.  23.  60. 522. 497.
  490.  25.  13.   0.   0.   0.   0.   0.]
 [  0.   0. 132. 345.  23.   0.   0.  32.  49.   0.   0.   0.   0. 123.
  147.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  88.  77. 189.  66.  28.   0.   0.  38.  20.   0.   0.  94. 229.
   39. 203. 282.  20.   0.   0. 110.  91. 101. 132. 171.   0.   0.   0.
    0.  45.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  84. 125.  31.  59.  30.   0. 131. 173. 127.  80.   0.   0.
   51.   0.   0.   0.   0.   0.   0.   0.  42.   0.   0.   0.   0.   0.
    0.  76.   0.   0.   0.  83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  19. 149.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 188. 141.  86. 560. 393. 329.  95.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 144. 519. 339.
  147. 348. 625. 601. 322. 502. 589. 610. 540.  77. 298. 224.  80. 172.
  442.  47.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  26.  80. 531. 240.   0.   0.   0. 415. 138.   0.  89.  18.
    0.  18. 116.  49.   0.   0. 201.  44.  28.  70. 183.  66. 163.  52.
   33.  72.  25.   0.  44. 219.  10.   0.]
 [  0.   0.   0.   0.  51. 370. 549. 477. 378. 224. 531. 546. 427.   0.
    0.   0.  38.  16.   0.   0.   0.  54.  24.   0.  55.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  48.   0.]
 [  0.   0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0. 226.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 107.  48.  34.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 36.  31.   0.   0.   0.   0.  86.   0.   0.   0.  55.   0.   0.  26.
    0.  34.   0. 148.   5.   0.   0.   0.   0.   0.   0.   0.   0.  84.
   89.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  37.  94.   0.   0.   0.   0.   0.   0.   0.   0. 107.   0.  19.
    0.   0.   0.   0.   0.   0.   0.   0.  24.   0.   0.   0.   0.   0.
    0.   0.   0.  24. 119. 136.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 183.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 483. 477.  78.   0.   0.   0.   0.
    0.   0. 100. 472. 311. 100. 284. 548.]
 [  0.   0.   0.   0.  50.   0.  48.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  32.  42.   0.   0.   0.   0.   0.   0.   0. 270.  93.
    0.   0.   0.   0.   0.  43.  43.  37.]
 [  0.  37. 120.  34.  21.  63.  31.  25.  43.   0. 136.  60.   0.   0.
   60.  70.   0.  45.   0.   0.   0.   0.   0.   0.   0.   0. 109.   0.
    0.   0.   0.  33.  71.   0. 121.  31.]
 [  0.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.   0.   0.   0.
    0. 115.  69.   0.   0.   0.   0.   0.  86.   0.   0.   0.   0.  21.
  106.   0.   0.   0.  55. 106.  47.   0.]
 [  0.   0.   0.   0.  87.   0.   0.   0.   0.   0.   0.  65.  53.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  80.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  87.   6.   0.  75.  89.   0.   0.  19.   0.   0.
    0.   0.   0.   0.   0.   0.  42.  12.   0.   0.   0.   0.   0.  53.
    0.   0.  35.   0.   0.  23.   0.   0.]
 [134.  71.  26.   0.   0.  39.  18.  98.   0.   0.   0.   0.   0.  88.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 100.   0.   0.   0.   0.   0.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 240. 268.   0.
    0.   0.   0.  29. 256.   0. 189. 123.  28.  24.   0.  44.  80.  26.
   28.   0.   0.  79.   0.  14.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  22.   0.  18.  22. 203.  19.   0.  80.
    0.  24. 102. 266.  29.   0.  91.  45.   0.   0.   0.  65.  57.  35.
    0.   0.   0.   0.   0.   0.   0.  36.]
 [ 34.   0. 230.   0.   0.  10. 245.   0.   0.   0.   0. 105.   0.   0.
   20.   0. 280.  87.   0.   0.   0.   0. 304.  76. 198.  18.  37.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 116. 181.   0.   0.   0.   0.   0.   0.  12.   0. 191. 453.
  322. 204.  16.   0.   0.   0.   0.   0.   0.  19. 137.  20.   0.   0.
    0.   0. 240.  54.   0.   0.   0.   0.]
 [ 55.  18. 138.  24.  14.  50.  20.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  22.   0.   0.   0.   0.   0.   0.  64.   0.   0.
    0.   0.  20.   0.  21.   0.   0.   0.]
 [429. 473. 504.   9.   0.   0.  31. 245.  26.   0.   0.   0.   0.   0.
   31.   0.   0.  49.  27.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 131.  23. 244. 515.]
 [301.  29.  69.  14.   0.   0.  47.  19.   0.  34.  70.  52.   0.   0.
    0.   0.  18.  31. 136.  21.  21.  79. 355. 133. 188.  32.   0.  16.
    0.  50.  26.  35. 238.  99. 113.  60.]
 [  0.   0.  83. 116.   0.   0.   0.   0.   0.  88.  89.   0.   0.   0.
    0.  71. 106.   0.   0.   0. 147.  98. 133. 364. 595.  57.  14.  24.
  189.   0.   0.   0.   0.   0.   0.   0.]
 [ 18.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  98. 100.   0.   0.   0.   0.   0.   0.   0.   0.  19.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  30.   0.   0.   0.  39.   0.   0.   0. 240.  36.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  26.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [101. 228. 339. 101.   0.   0.   0. 107. 247.  35.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  25. 244. 549. 487. 124.   0.]
 [126.  72.  21.  67.  22.  51.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 156. 187.   0.   0.   0.  20.   0.   0.   0.   0.  39.   0.
    0.   0.   0.  47.   0.   0.   0.   0.   0.  52.  18.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  31. 178. 351.  58. 373. 158.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  64.  31.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  32.  69. 476. 533. 521.  93.
   19. 187.   0.  91. 455. 506. 477. 122.]
 [  0.  29.  21. 217. 237. 364.  46.  18.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0. 111.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  26. 244.  29.  61. 201. 313. 303.   0.   0. 158.  50.  56.  18.
   14.  72. 191. 131.  23.  25.   0.   0.]
 [554. 456.   0.   0.   0.   0.   0.   0.   0.   0.  40.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 204.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[553. 537. 111. 372. 105.  86. 375. 290. 203. 427. 263.   0. 127.   0.
    0.   0.  52.   0. 130.  55. 471. 297. 114. 157.   0.   0.  19.   0.
   17.   0.   0.   0.   0.   0.   0. 245.]
 [  0.   0. 139.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  21.   0. 184.  60.
    0.   0.   0.   0.   0.  52.   0.   0.]
 [150.   0.  42.  24.   0.   0.   0.   0.   0.   0.   0. 426. 284.   0.
    0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.  43.   0.   0.
   20.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 203.   0.   0. 108.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 262.  24.  69. 319.   0.   0.   0.
    0.   0.  30.   0.   0.  54.  44.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 153.   8.   0.  76.   0.   0. 116.  28.   0.   0. 501. 275.   0.
    0.  63.   0.   0.   0.   0.   0.   0.]
 [  0. 130.  40.   0.  71.   0. 120.   0.  28.  16.   0.   0.   0.   0.
    0.  18.   0.   0.   0.   0.   0.  47.  79.  18.   0.  39.   0.   0.
    0.  59.   0.   0.   0.   0.   0.   0.]
 [ 21. 114. 114. 255.  72.   0.   0.   0.   0.   0.   0.   0.  25.   0.
    0.   0.  50. 124. 119.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 105. 274.  13.   0.   0.   0.   0.   0.   0.   0.   0. 161.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 422.   0.  33.   0.   0.
  188.   0.   0.  97.   0.   0.   0.  18.  29.   0.  63. 168.  18. 324.
   16.   0.   0.   0. 338.   0.  33.   0.]
 [  0.   0. 139. 104.   0.   0.  36.   0.  38. 269.   0.   0.  65. 468.
  573. 550. 555. 543. 520. 551. 543. 182.  18.  23.  88.   0.  24.  31.
    0. 240.  20.  33.  19.  71.  45.  18.]
 [  0.   0.   0.  14.   0.   0.  78.   0.   0.   0.   0.   0.   0.   0.
    0. 121.   9.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  40.
   39.  53.   0. 168. 110. 215.  26.   0.]
 [592. 545.  65.  32.  68. 111. 121. 204. 395.  14.  32.   0. 232. 386.
    0.   0.  51.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   50.  16. 112.   0.   0.   0.   0.   0.]
 [  0. 189. 130.  45.   0.   0. 205.   0.  19.  18.   0.  81. 301.  31.
  156.  21.  58.  15.   0.  26.   0.   0.   0.   0.   0.  96.   0.   0.
    0.  19.   0.   0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.   0.  60.  59. 360.  95.   0.  27. 125. 153.  91.
   57.   0.   0.   0.   0.   0.   0.  46.  75.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  22. 471.  14.   0. 419. 107.   0.   0.   0.   0.   0.   0.
   19.  48.  19.  16.   0.  21.   0.   0.   0.  32.   0.   0.   0. 169.
    0.   0.   0.   0.   0. 139.  76.  14.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  75. 210.  47.  48.   0.   0.
    0.   0.   0.   0.   0.   0.  54.   0.]
 [128.   0.   0.   0.   0.  66.   0.  22.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  26.  73.  24.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  19.   0.   0.]
 [  0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 158.   0.  97. 108.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  87. 376.   0.   0.  25.]
 [  0.   0.   0.   0.   0.  81. 149.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 177. 255. 343.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  43.  49.  18.  19.  23.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  30.   0. 104.  90. 158.  54.  40. 185.   0.  45.
   25.   0.  77. 189. 390. 529. 355.   0.]
 [140. 202.   0.  66. 247.  83.   0.   0.   0. 109.  82. 101. 230.  90.
    0. 237. 422.   0.  39. 106.   0.   0.   0.  29.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  17.  37.   0.  20.   0.   0.  93.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  93. 166.  22.   0.   0.   0. 120. 196.  14.  30.
    0.   0.   0.  79. 154.   0.   0.   0.]
 [  0.   0.   0.  80. 429. 427. 503.  41.  59.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [412. 186.  20.   0. 178. 135.   0.   0.   0.   0.  93.   0.   0.   0.
    0.   0.   0.   0. 126.   0.   0.   0.   0.   0.  18.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  53. 161. 100.  86.   0.   0.  79.   0.   0.   0.   0. 126.  53.
   34.   0.   0.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 119.   0.   0. 225.]
 [  0.   0.   0.  62.  41.  20.   0.   0.   0.   0.  19.   0.  54.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   25.   0.   0.   0.  45.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  31.  33.   0.   0.   0.   0.
  156. 141.   0.  20.   0.   0.   0. 109.  28.  19.  77.  20.   0.  85.
    0. 132. 173. 235.  98. 187. 121. 135.]
 [145. 100.  29.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  70.   0. 136.   0.   0.   0.  87.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 294.]
 [ 97.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  69. 391.  14. 267.  89.   0.   0.   0.   0.   0. 168.
  208. 265.  17.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 25.   0.   0.   0.   0.   0.   0.  36.  77.   0. 194.  59.  74.   0.
   60. 123.  45.   0.   0.   0.   0.   0.   0.   0.   0.   0. 330. 266.
    0.  59.   0. 497. 520. 218.  72.  55.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  19. 335. 321. 307.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  331. 565.  40.   0.   0.   0.   0. 205.]
 [ 14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  26.   0.   0.
    0.   0.   0.  23.  35.   0.   0.   0.   0.  78. 180.   0.   0.   0.
  190. 108.  91.  28.   0.   0.   0.  40.]
 [  0.   0.   0.   0.   0.   0.   0. 153. 188.   0.   0. 108. 137.   0.
    0.   0.   0.  98.   0.  45.  22.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  52.  77.   0.  34.]
 [  0.   0.   0.   0.   0.   0.  63.  78.   0.  21.   0. 406.   0.  61.
  249.  76.  59. 126.  32. 286. 167. 182. 126.   0.  39.  37.   0. 152.
   42.   0.   0.   0.   0.   0.  73.   0.]
 [ 27.  18.   0.  38.  12.  25. 107.   0.   0.  21.   0.  62.   0.  33.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  20.   0. 105.
   21.  74.  29.  19.   0.  24.  52.  65.]
 [  0.   0.  91.   0. 155.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   37.   0.   0.   0.   0.   0.   0.  94.  28.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 169. 151.  64.   0.]
 [ 91.   0.   0.   0.  45.   0.   0.  76. 157.   0.   0.  59. 297.  61.
   85.   0. 327.   0.   0.   0.   0.   0.  76. 157. 109. 242. 235. 384.
  383. 355.  56. 249.   0.  29.   0.  33.]
 [  0.   0.   0.   0.   0.   0.  75. 165.   0.   0.   0.   0.   0. 174.
    0.   0.   0.   0.   0.  65. 197.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  48. 132. 135.  65. 208.  30.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 15.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 356. 468.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  19.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  82.   0.   0.   0.   0.  18.   0. 105.  27.   0.  33. 114.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  40.  76.  40.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  24.
    0.   0.  93.   0.   0.  78.   0.   0.]
 [ 74.  46. 126.  81. 167.  38.  24. 142.  77.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  33. 265.  26.  15.   0.   0.   0.   0.   0. 136.
    0.   0.  91.  55.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 134.   0.   0.   0.   0.   0.
   40.   0.   0.  38.   0.  21.   0.   0.   0.   0.   0.   0.   0.  56.
    0.  88. 109.   0.   0.   0.   0.   0.]
 [ 81.  85.  20.  95. 172. 204. 229.  44.  44.  43. 204. 123.  20. 153.
  169. 106. 158. 110. 237.  44. 245. 164. 102. 290.  92.  92.  18.   0.
   76.  34.  19.   0.   0. 127. 607. 769.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   73. 161.  18.  54. 328. 111. 112.  71.]
 [ 49.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  56.   0. 365.
  511. 521. 180.   0.   0.   0.   0.   0.  47.   0.   0.   0.   0.   0.
   75.   0.  83.   0.   0. 141. 143.  78.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  19.  45.   0.   0.
   45. 107.  70.   0.  21.  74.  19. 488. 562.   0.   0.   0. 468. 486.
    0.   0. 350. 416.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 171. 487. 517. 316.  52. 139.   0.   0.   0.
    0.   0.   0.  21.   0.   0.   0.   0.]
 [  0.  93.   0.   0.   0.   0.   0.  69.   0.   0.  23.   0.  43.   0.
    0.   0.   0.  47. 139.   0.  49.   0.   0.   0.  23.  40.  84.  71.
   19.   0.  17.  30.   0.   0.   0.   0.]
 [ 20.  95.  72.  87.  19.   0.  53.  74.   0.   0.  27.  28.  39.  97.
   23.  22.  44.   0.   0.   0.   0. 113.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 54.  36.   0.  73.   0.  94.  40.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  23.  40.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  19.  85.  23.  87.  56.  80.  23.]
 [  0.  66. 110.   0.  97.  19.  51.  53. 247. 139.  15. 182. 443. 274.
  527. 561. 559. 438. 542. 495. 489. 134.  41.  35.   0.   0.   0. 189.
  325. 416. 553. 583.  98.  76.   0.   0.]
 [  0.  47.   0.  13.  58.  57.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 181.   0.   0.   0.   0.   0. 222. 571. 559. 351. 124.  23.  98.
    0.   0.   0.   0.   0.   0.   0.  94.   0.   0. 436. 478. 161. 400.
  230.  18. 154.  23. 121. 568. 233.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 106.
    0.   0.   0.   0.   0.   0.   0.   0.   0.  18. 252.  69.   0.   0.
    0.   0. 122.   0.   0.   0.  86. 135.]
 [  0.   0.   0.  35.   0.  37.   0.   0.  23.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  19.   0.   0.   0.  16.  25.  35.   0.
    0.   0.   0.  27.   0.  13.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  32.  22.   0.   0.   0. 111.  75. 150.  17.  69.  27.   0.   0.
    0. 144.  59.  31.   0.   0.  64.  36.]
 [  0.   0.   0.   0.   0.   0. 104.   0.   0.  37.   0.   0.   0.   0.
    0.  17.   0.   0. 441. 529. 431.   0.   0.  34.  18.   0.   0.   0.
    0.   0.  33.  76.   0.   0.   0.   0.]
 [  0. 121.   0.   0.   0.   0.  24.  19.  13. 145.   0.   0.   0.  75.
    0.   0.   0.  42.  18.   0.  52.  56.   0.  18.  42.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  27.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 59.   0.   0.   0.   0.   0.   0.   0.   0.  22.   0.   0.   0.   0.
    0.  29.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  67.  39. 111. 142.]
 [  0.   0.   0.   0.   0.  19.   0.  28.  41.   0.  63.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 107.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 90.  79.  61.   0.   0.   0. 138.  48. 127. 179. 125.   0.  38.  12.
  109. 295. 126.  39. 293. 320. 266. 158.   0. 494. 166.  73.  42.  81.
  103. 160.  95. 134. 103. 114.  67. 176.]
 [  0. 386. 179.   0.  55.   0.   0.  39.   0.  38.  41.   0.   0.   0.
    0.  67.   0.   0.   0.   0.   0.  23.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 179. 156.   0.   0.   0.   0.   0.  62.  50.   0.   0.
    0.   0.  28.   0.   0.   0.  68.  19.  32.  45.  40.  24.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  22.]
 [ 25.   0.   0.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0.  21.
  126. 160.   0.   0.   0.   0. 107.   0.  28.  15.   0.   0.   0.   0.
   37.   0.   0. 148. 189. 113.  49.   0.]
 [  0.   0.   0.  19.  35.   0.   0.  44.   0.   0.   0.   0.   0.  33.
  264.   0.   0. 133.  30.  27.   0.   0.   0.   0.  41.  46.   0.   0.
    0.   0.  42.  78.   0.  69.  48.   0.]
 [179. 120. 236. 118. 112. 150.  56. 242.  76.   0.   0.   0.   0.   0.
   38.  71.  32.  55.  50.  39. 141.   0.   0.  20. 409. 103.  53.  31.
  279. 125.  36.  64.  57.  74.  68.   0.]
 [  0.  91. 462. 556. 435. 121.   0.  77.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  16.  28.  14.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  16.  40.   0.   0.   0.  18.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  39.   0.   0.   0.   0.   0.   0.  10.
    0.  19.   0.   0.   0.  22.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 124. 519. 515. 417. 464.
  516. 483. 500. 505. 247.  33.   0.   0.]
 [  0.  88.   0.   0.   0.   0.  96.  59.  70.   0.  68.   0.  52. 103.
  330.   0.   0.   0.  18.  26.   0. 130.   0.   0.   0.   0.  47.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  17.  69.  16.   0.  23.   0. 207. 349.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  23. 518. 119.  84.   0.   0.
    0.  12.   0. 244. 213. 144. 127.  37.  40.   0.  45.  17.  39.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 13.  93. 116.   0. 155.  96. 108.  91.   0.  77.  99.  38.   0. 121.
  112. 106.  63.   0.  53.  17. 226.  52.  32.   0. 103.  70. 111. 109.
   32.   0. 110. 207.  64. 135. 107. 168.]
 [111. 300.  65.   0.  24.   0.   0.   0.   0.   0.   0.   0.  37.   0.
  120.  24.   0. 257.   0. 306. 235.   0.  38. 243. 133.  23. 114.   0.
    0.   0.  20.   0.   0. 208. 189.  32.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  33.   0. 343. 543. 533. 109.  13.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  92.   0.   0.   0.   0.]
 [127.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.  29.
    0. 123.  53.   0.   0.   0.  65. 113.   0.   0.  26.  68.  28.  51.
   19.   0.   0.  54.  19.   0.   0.  27.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 58. 118.  39.   0.  56.  45.  58. 115.  47.  87.   0.  76.   0.   0.
    0.   0.   0.  51.   0.   0.  48.   0.  78.  18.   0.   0.   0.   0.
   82.  21.   0.   0.   0.   0.  16.   0.]
 [  0.  52. 196.  13.  23.   0.   0.   0.  14.   0.   0.   0.   0.   0.
    0.   0.   0. 492. 385.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  22.   0.   0. 121.   0.   0.  82.  33.
    0.   0.   0.   0.   0.  20.  73.   0. 109.   0.   0. 113. 175.   0.
  206.  23.  83. 119.  22.   0.   0.   0.]
 [  0.   0. 197.   0.  45.  14.  38.  47.   0.  33.  28.  32.   0.  24.
   14.   0.   0.   0.  37.  19.   0.   0.   0.   0.  37.  15.   0.   0.
   98. 141.  53.   0.  23.  41.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  67.  15.  33.
    0.  40.  75. 332. 527. 114.   0.   0. 554. 493.  23.   0.  51.   0.
    0.   0.  66. 200. 101.   0.  35.  35.]
 [214.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 141. 587. 492.
   47.   0.   0.   0.  24.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  32. 291. 453. 275. 285. 500. 192.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 227.  60.   0. 100.  95. 158.   0.  47.  18.   0.   0. 101.   0.
    0.  90.   0.   0.   0.   0.   0.   0.]
 [559.  95.   7.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  52.
    0.   0.   0.   0.   0.   0. 496. 516. 341.  60.   0. 131. 491. 295.
  562. 555. 530.   0.   0.   0.   0.   0.]
 [  0.   0.  39. 217. 113. 309. 107.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  49.  19.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 60.  33. 154.  14.  38.   0.   0.   0.   0.   0.  45.  66.  24.  68.
  193.   0.   0.   0.   0.   0.   0.  59.  18.   0.   0.  16.  38.  87.
   31.  85.   0.   0.   0.   0.   0.   0.]
 [ 69.  38.   0. 117.  56.   0.   0.   0. 193. 443. 375.   0. 274. 416.
    0.  24. 122. 177. 143. 246. 194.   0.   0.  62.   0. 121. 230. 106.
   33. 158. 148.  72.  22. 492. 147.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  20.
  120. 443.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   32. 487.  90.   0.   0.   0.   0.   0.]
 [  0.   0.  54.  69.   0. 110.   0.   0.   0.   0.   0.   0. 114. 189.
   19.  37.   0. 154.  48.   0.   0.   0.   0. 122. 139.  24.   0.  49.
  100.   0.  80. 131.  50.   0.  18.  47.]
 [ 50.   0. 245. 552. 486. 578. 346. 286.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0. 103.  92.  97.   0.  85.  44.  68.  27.  19. 145.   0.  35.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  30.  60.
    0.   0.   0.  66.  23.  91.   0.   0.]
 [  0.   0.   0. 120.   0. 111.   0.  42.  88.  32.   0.   0.   0.   0.
    0.   0.   0.  85. 266. 162.   0. 409.   0.  45. 170.  94.  21.  49.
    0.   0. 148.  94.  21.   0.  13.   0.]
 [  0.   0.  13.   0.   0.   0.  25.  33. 387. 260. 122.  18.  42.  43.
   70.   0.  23.  85.  49.  66.  32.   0. 500. 303.  44. 158.   0.   0.
    0.   0.   0.   0.   0.  63.  49.  33.]
 [ 32.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 237.  64.  24.   0.   0.   0.   0.  18.
   21.   0.   0. 109. 144.   0. 115.  82.]
 [  0.   0.   0.  49. 181. 252.  66. 104.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 211. 179. 107.   0.
    0.   0.   0.   0.   0.   0.   0.  90.]
 [117.   0.   0. 111. 294. 450. 589. 441.  98.  72.   0.   0.   0.   0.
    0.   0.   0.   0.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 233. 247.  37.   0.   0.   0.]
 [  0.   0.   0.  35.   0.  33. 124.   0.   0.   0.   0.   0.  21.   0.
    0.   0.   0.  51.   0.   0.  44.  19.   0.   0.  24.  22. 129.   0.
    0.  30.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  80. 211. 203. 151. 656. 292.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 34.  41.   0.   0. 192. 136.  69.   0.   0.  62.  94.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 144.   0. 190.
  150.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  84. 355. 248.
   40.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  34.  29.   0.  20.   0.  46.   0.   0.   0.   0.   0.   0.   0.
    0.  49.   0.   0.   0.  54.   0.   0.   0.   0.  44.   0.  82.  79.
   18.  19.  79.  37.  60.   0.  54.  54.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  19.   0. 147. 221. 210.  78. 119. 227.   0. 205. 560. 551.
  318. 505. 559. 369. 303. 301. 573. 588.]
 [  0.   0.   0.   0.  33.  19.  51.  19.   0.   0.   0.  42.   0.  23.
   31.  79.  19.  18.  50.   0.  40.  34.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 22.   4.   0.   0.   0.   0. 103. 128.   0.   0.   0.   0.  50.  88.
  528.  35.   0.  40.   0. 152. 701. 247.   0.   0.   0.  35. 254.  69.
   14.   0.  68. 374.   0.   0.   0.   0.]
 [  0.   0.  22.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  38. 120.  43.   0.   0.  28.  28.   0.   0.   0.
    0.   0.   0.   0.   0. 150.  54.   0.]
 [  0.   0. 312.   0.   0.  55. 141.   0.   0.  21.   0.   0.  44.  22.
    0.   0.   0.   0.   0.   0.   0.  34.   0.  18.   0.  19.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 51.   0.  37.  24.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  70.   0.   0.   0.   0.   0.   0.  25.   0.   0.   0.   0.
    0.   0.   0.  43.   0.   0.  26.   0.]
 [  0.   0.   0. 175. 197. 223.   0.   0.  83.   0.   0.   0.  70.  87.
  273. 173. 235. 159. 337. 151.   0.   0.   0.   0.  43.  34.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  32.   0.  26.
   18.   0.   0.  20.   0.   0.  26.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  31.   0.
  180.  22.  46.  38.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 101. 185.   0.   0.  60.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 96. 197. 115.  80.   0.   0.   0.   0.   0.   0.   0.   0.   0.  79.
   33.   0.  42.  19.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  18.  49.  94.   0.   0.   0.   0.]
 [  0. 108. 267.  84.   0.   0.  75.   0.  23.   0.   0.   0.   0.  25.
    0.  86.   0.   0. 216.  17.   0. 112.  64.  39.   0.   0.   0.   0.
   42.   0.   0.   0.   0.   0.   0. 206.]
 [  0.   0. 214. 118.   0.  68.   0.   0. 149. 577. 221.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 216. 509. 205.   0.   0.   0.   0.]
 [  0.  22.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  37.
    0. 528. 566. 557. 152.  19.   0.   0.   0.   0. 483. 548. 419.  65.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 14. 383. 499. 523. 370. 126. 142.   0. 459.   0.   0.   0.   0.   0.
   23. 505. 155. 173. 398. 385. 139.  65.   0. 107. 122. 301. 320.   0.
    0.   0.   0.   0.  83. 115.  55.  28.]
 [126.  33. 150.  50. 157. 139.  53.  50.  63.  14.  79.  47.  45.  71.
   81.   0.  35.   0.  26.  25.  36.  19.  22.  20.  18.  21. 123.  75.
    0.   0.   0.   0.   0.   0.  19.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 331. 100.   0.   0.  19. 331. 526.  23.  85.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0. 155. 498. 349. 115.   0.   0.]
 [  0.  32.  82.   0.   0.  40.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  24.  82.  35.  66.  93.  43.  35.   0.   0.
   85.  34.  37.   0.   0.   0.   0. 111.]
 [ 25.   0.   0.   0.   0. 243.  37.  18.   0. 197.  41.   0.   0.   0.
  105.   0.  33.   0.   0.  56. 262.   0.  59. 237. 109.   0.  21.  31.
   31.  68.  24.  19.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  18.  68.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  47.   0.   0.   0.   0.   0.   0.   0.   0.  71.
  127.   0.   0.  26.  19.   0.   0.   0.]
 [ 34.   0.   0.   0. 140. 197. 199. 262. 258.   0.   0.   0. 241.  48.
    0.  90. 191. 268. 168. 152. 267. 197.   0.   0. 149.  72. 159. 434.
  269. 345. 297. 358. 201. 243. 241. 457.]
 [  0.   0.   0.   0.   0.  64. 214.   0.  72.  40. 435. 196.   0.  13.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  42.
    0.  47.  40.  31.  21.   0.   0.   0.]
 [  0.   0.   0.   0.  16.  22.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  50. 519. 400. 479. 473. 529. 133.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 254.  26.  42.   0.  63.   0.  81.  67. 417.   0.   0.   0.
   42.  48.  99.   0.   0.  65.  37. 114.   3.   0. 207.   0.  27.   0.
    0.   0.   0.   0.   0.   0.  19. 143.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  24.   0.  57. 104.  51.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  11.  37.   0. 103. 289.   0.   0.   0.   0.   0.  39.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[ 97.   0.   0.   0.   0.   0.  19. 159.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  19.   0.   0.
  181. 109. 395. 538. 540. 541. 531. 532. 517. 129.   0.   0.   0.   0.
    0.  81.   0.   0.   0.   0.   0.   0.]
 [ 74.   0.  28.   0.   0.   0.   0.   0.   0.  47.  38.  16.   0. 151.
  106.  47.  91.   0.   0.   0. 274. 242. 233. 295. 100. 172.  45.  56.
  124.   0.   0.   0.  48.  20.  49.   0.]
 [ 89.  66.  56.  19.  18.  39.  26.  43.   0.  21.   0.   0.   0.   0.
    0.  47.  56.  13.   0.   0.  48.   0.  41.   0.  26.  19.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 193. 243.  45.   7.   0.  84. 489.   0.   0.   0.   0.
    0.   0.   0.   0.  49.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  73.   0.   0.   0.   0.  25. 304. 303. 422. 523. 521. 531. 513.
  515. 340. 320. 310. 598. 597. 588. 596. 563. 173.   0.   0.   0.   0.
    0. 102.  20.   0.   0.  30.   0.   0.]
 [ 15.   0.   0.  29.   0.   0.  48.  12.   0.   0.  27.   0.   0.  19.
    0.   0.  38.  75.  42.  68. 200. 277. 112. 316. 159.  21. 121. 157.
  184.  87.  82.   0. 187.  37.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  35.   0.   0.   0.   0.   0.   0.   0.  49.
  209. 287. 202. 103.  79.  62.  82. 127.   0. 134. 185.   0.  50.  35.
    0.   0.  20. 147. 138. 127.   0.  81.]
 [  0.   0.   0.   0.   0.  39.   0.   0.   0.   0.   0.   0.   0.   0.
   93.  39.   0.   0.   0.   0.  92.   0.   0.   0.  21.   0.  19.  56.
   43.   0.   0.   0.   0.   0.   0.  16.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  24.  22.  14.   0.   0. 159.  83. 353. 551.  64. 176.   0.  93.
  558. 533. 502.  45.  23.   0.   0.   0.]
 [  0.  55. 153. 204. 216. 134. 201. 193. 200. 183.  35.  33. 230. 203.
   98. 218. 257. 223. 289. 261. 142.  26.   0.  19.   0.   0. 278. 226.
  222. 170.   0.  35. 204. 166. 244. 205.]
 [  0.   0. 114. 224. 117.   0.   0.   0.   0.   0. 149.  39. 135.  38.
   60.   0.  13.   0.  45.  32.  64.   0.   0.  34.  62. 126.  14.  57.
   44.  29.  84.  51.   0. 190. 187.  54.]
 [ 60.   0. 130. 199.  17.  55.  14.  92.  34.   0.   0.  88.  73.   0.
   87.   0.   0.   0.   0.   0.  55.  17.  70.  87.   0.   0.   0.  31.
   82.  26.  81.   0.   0.   0.   0. 186.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  48.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  45.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  58.  35. 111.  63.   0.
  102.  19.   0.   0.  61.   0.   0.   0.   0.  21.   0.   0.   0.   0.
    0. 161. 160.   0.  30.  50.  40.   0.]
 [  0.  32.   0.   0.  24.   0.  35.   0.   0.  22.   0.   0.  42.   0.
    0.   0.   0. 200. 150.  77.  19.  43.  24.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  46.  38.]
 [361.   0. 199.   0.   0.   0.   0.   0.   0.   0.   0.   0.  27.   0.
    0.   0.   0.   0.   0.   0.   0.  68. 102. 118.   0.  61.   0.   0.
    0.   0.   0.   0.   0.  57.   0.   0.]
 [  0.  50.  26.   0.   0.   0.  75.   0.   0.   0.   0.   0.  63.  34.
    0.   0.   0.   0.   0.  29. 106. 384. 387.  96.  85. 549. 130. 169.
  181.  25.  49.  55.   0.  22. 155.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  93. 135.   0.   0.
    0.   0. 275. 369. 592. 558. 168.  36.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [215. 345. 395.  86. 292.  81. 118. 213. 247.  18.   0.  24. 191. 285.
    0.  12.   0.   0.   0.  25.   0.  52. 172. 173.  78.  25.  19.  29.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 24.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  74.   0. 164.  95.  33.   0.   0.  71.   6.
    0.   0.   0.   0.  24.   0.   0.  30.]
 [ 20.   0.   0.  64. 148.   0.  86.  84.  62.   0.   0.  77.   0.   0.
    0.   0. 125.   0.  93. 282. 155.  68. 239.  25. 238. 276. 149.   0.
  238. 177.  56. 231.  36.   0. 120.  91.]
 [  0.  44.  53.   0.  31. 227. 229.  51. 169.  83.   0.   0.   0.   0.
  270.  59.  22.   0.  40.  18.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 21. 243.  61.  19.   0.   0.   0.  25.   0.  51. 209.  11.   0.   0.
   35. 141.   0.  19.  18.  82.  26.  23.  18.   0.   0.   0.  28.   0.
    0.   0.  61.  29.   0.   0.   0.   0.]
 [164.  20. 390. 599. 486.  80.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  20.   0.  44.   0. 212.  36. 357.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 77.  32.   0.   0. 319.  19.  13.   0.   0.   0.  81.  62.   0.   0.
    0.   0.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   22.   0.   0.   0.   0.  29.  46.   0.]
 [  0.  63.  20. 163. 224. 192.  57.   0.  91. 266.  28.   0.   0.   0.
   75.  71.   0.  30.   0.   0.   0.  52.   0.   0.   0.   0.  14.  30.
  475. 514. 464. 499. 186.   0.   0.   0.]
 [ 36.  63.  89.   0.   0.   0.   0.   0.  16.  38.   0.  21.  30.  22.
   74.  82.  67.  79.   0.   0.  12.  49.  32.   0.   0.   0.  62. 157.
  288.   0. 337.  43.   0.  90.   0.   0.]
 [ 21.   0.   0.  27.  26. 150.  47. 100. 111. 105. 153. 180.   0.   0.
    0. 152.  29.   0.  21.  36.   0.  92.   0.   0.   0.   0.   0.   0.
    0.   0.  53. 288. 215.  29. 117.   0.]
 [ 19.   0.   0.   0.  22.   0.   0.   0.   0.   0. 154.   0.  19.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 138.
  152. 222.  26.   0.   0. 187. 187.   0.]
 [  0.   0.   0.   0.   0.   0. 259.  62. 134.  35. 168.  56. 280. 254.
    0.  19.   0.  78. 131.  27.   0.  54.  27.   0.  36.   0.  18.  52.
  216.  27.   0.  19.  22. 245. 126.   0.]
 [140.  32.   0.   0.   0.   0.   0.   0.   0.  96.  18.   0.   0.   0.
    0.   0.   0.   0.  69.   0.   0.   0.   0.  19.  33.  61.  70.   0.
    0.   0. 150.   0.  31.   0.  88.   0.]
 [ 37.   0.   0.   0.   0.   0.   0. 107.   0.   0.   0. 109.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  65.  48.  68.  47.  85.  79.  76.
    0.  40.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  30.  24.   0.  47.   0.   0.   0.   0. 121.   0.
    0.   0.   0.   0.   0.  79.   0.   0.  99.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  28.   0.   0.   0.]
 [ 47.   0.  78.   0. 202.  31.  40.  32.  20.  67.  57.   0.   0.   0.
    0.   0.   0.   0.  30.  62.  47.   0.   0.   0.   0.  70. 113.  43.
    0.   0.   0.   0.   0.  19.  24.   0.]
 [269. 592. 614. 586. 636. 701. 628. 638. 681. 629.  67. 267. 208.  11.
  275. 332.   0.  21.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  72. 143.  56.   0.   0.  20.  57.]
 [  0.   0.   0. 142.   0.  36.  35.   0.  60. 128.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0.  86.   0.   0. 103.  11.   0.   0.   0.   0.  37.   0.
    0.   0.   0.   0.  25.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  99. 173.   0.  31.  79.   0.   0.]
 [  0.   0.   0. 163. 528. 327. 133.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 106. 542. 232.
    0. 151. 306. 193. 134.   0.   0.   0.]
 [  0.   0.   0.   0.  21.  77. 139.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  23.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 180.  76.  71. 488.]
 [ 48.  73. 221. 244. 544. 542. 540. 472.   0.   0.  68.  36.   0.   0.
   88.  28.  86. 159. 133.  92.   0.   0.   0.   0.   0.   0.   0.  19.
   94.   0.  57.  48.   0. 119.  39.  34.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  20. 136. 134.  62. 258. 197. 134.  53.
   19.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  48.
   30.   0.   0.  52. 115. 191.  83. 279.   0.  22. 134. 141.  71.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  61.  22.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 220.   0.   0.   0.   0.
   18.  22.  24.   0.  78.  14.  34.   0.]
 [590. 631. 456.   0.   0.   0.   0. 454. 200. 132.   0.   0.   0.   0.
   18.  23.  55.   0.   0.  24.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  29.   0.  36.  95.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.
  103.   0.   0.  23. 258. 352.  23.   0.   0. 273. 105.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  89.   0.   0.   0.   0.  45.   0.   0.
    0.  91.  46.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 126. 137.   0.   0.   0.]
 [513. 582. 181.   0.   0.  25.   0.   0.   0.   0.   0. 170. 107.   0.
    0.  29.   0.   0.   0.   0.   0.   0.   0.   0.  55.  20.   0.   0.
   22.  18.   0. 103. 356.  81. 168.  50.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  56.   0.   0.  70. 222. 121.
  179. 198. 275. 260. 162.  57.   0. 262. 191. 153.  96.   0.   0.   0.
    0. 136. 155.  42.  35.  45.  88. 137.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 141. 539. 352.  78.  24.  60.
   73. 142. 111.   0.  28.   0.  65. 101. 149. 526.  77.   0. 417.   4.
   23.   0. 177.  64.   0.   0.   0.   0.]
 [279.  13.   0. 265.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  19.  14.
   22.  93.   0.   0.   0.   0.   0.   0.]
 [358. 430. 484. 599. 230.   0.  31. 155.  99. 190.  50. 355. 391.  66.
   95.  85. 216. 270. 121.   0.   0.   0. 506.  20.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [587. 239.   0.  88. 138.   0.   0.   0.   0. 372. 447. 275. 274. 587.
  650. 595. 626. 649. 639. 566. 628. 142. 196. 107. 501. 412.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [209.  50. 111.   0.   0.   0.   0.   0. 141.  37.   0.  30.   0.   0.
   23.   0.   0.   0.   0.  22.  24.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.  39.  33. 261.]
 [ 88.  50.  39. 101.  95.  39.  19.  94.   0.   0.   0.  18.  27.   0.
    0. 280. 538.  62. 226. 135.  56. 210. 370. 507. 257. 183.  94.   0.
   28.   0. 177.  39. 226.  90. 144.  67.]
 [210.  13.   0.  77.  20.  40.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.  42.  68.  53.   0.   0.   0.  21.  14.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 214.  59.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  29. 157.  34. 146.   0.   0.   0.   0.  87.   0. 162. 134. 165.
  231.  22.   0.   0.   0. 237.  51.  67.]]
[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[224.  78.   0.  40.  69. 107.  91.  64. 168.   0.  25.  18.  73.   0.
    0.   0.   0.   0.   0.   0.  25. 157.  62.   0.   0.   0.   0.   0.
   73. 102.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 119. 131.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 72. 138. 127.  92.  22.  34.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0. 391. 486. 205.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 41.  35. 289. 111.   0.   0.   0.   0.  80.   0.  84.   0.   0.   0.
    0.   0.   0.  18.   0.   0.   0.   0.  76. 119. 226. 522. 521. 403.
  441. 285.   0.   0.   0.   0.   0.   0.]
 [267. 157.   0.   0.   0.   0.   0.   0.   0.  18.   0.   0.  29.  37.
    0. 259. 133.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0. 115. 191.  82. 122.  78.  89.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  34.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 23.   0.   0.   0.   0. 136.  95.   0.   0. 146.  38.  43.   0.  53.
    0.   0.   0.  42.  34.  42. 129.   0.   0.   0.   0.   0. 129. 195.
   28.   0.   0.   0.  52.   0.   0.   0.]
 [ 28. 280.  59.  65. 181. 156. 119. 133.   0.   0.   0.  73.  14.   0.
   87.  87.   0.   0.   0.   0.   0.   0.   0.   0.   0.  96. 273.  53.
   39.   0.   0. 132. 113. 132. 131.   0.]
 [ 38. 251.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   56.   0.  20.  67.   0.   0.   0. 260. 114. 366. 117.   0.   0.  22.
    0.   0.   0.   0.  37.   0.   0.  20.]
 [  0.   0. 105.  24.   0.   0.   0.   0.  17.   0.   0.   0.  82.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.  98.  81.   0.   0.]
 [  0.   0.  23.  19.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.  25.   0. 423. 450. 323.   0.  70.  73.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [561. 551. 509. 505. 530. 550. 511. 519. 230.  22.   0.   0.   0.  30.
   19.   0.   0.   0.   0.  43. 217.   0.   0.   0.   0.  51.   0.   0.
   57.   0. 219. 158.   0.   0.   0.  44.]
 [  0.   0.   0. 187. 106. 211.  88. 212. 140. 127. 117.  84. 119. 174.
  147.  18.  93.  75.  97.  73. 248.  99. 186. 219.  48. 110.   0.  28.
   85. 205.  23.  95.  20.  44. 196.  68.]
 [  0.   0.   0.   0. 316. 105.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 127. 183.   0.   0.   0.   0. 118. 280.   0.
    0.   0.  42.  35.  82. 179.   0. 205.]
 [  0.   0.  58.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  29.  41.
    0.   0.   0.   0.   0.   0.   0.  57.]
 [146.  87. 127. 201.  79.  72.  59.  18.  53.  65.   0.  92. 327. 185.
    0.   0. 126.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 404. 478.]
 [  0.   0.   0.  84. 108.   0.   0.   0.   0.   0.   0.   0.   0.  49.

[[[  0.   0.   0. ...   0.  26.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  68.  25.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  42.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  24.  18.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 ...

 [[  0.   0.   0. ...   0.   0. 296.]
  [218.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.  22.  66.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ... 103. 506. 506.]
  [144.  74. 100. ...  86. 308. 120.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]]
[[  0.   0.   0. 253. 114.  59. 151.  31. 133.  60. 113.  34. 207. 208.
   16. 124.  46. 151. 214.  41. 154. 186. 281. 251. 156. 115. 109.   0.
    0.  53.  85.  55.  55. 107.  25. 178.]
 [  0.   0.   0.   0.   0.   0.   0.  90.  69.   0.  99.   0.   0.   0.
    0.   0. 128. 187. 114.  42. 174. 115.  38.  52.  28.   0.   0. 428.
  276. 109.  18.   0.  23.   0.   0.   0.]
 [ 19.   0.   0.   0. 113.  70.  37.  91.  24.  65. 275.   0. 256.   0.
    0.   0. 131. 187.   0.   0.   0.   0.  68.  55.  51.  58.  92. 319.
   28.  38.  14.  26. 132.  19.   0.  76.]
 [  0.  29. 169.   0.  20.   0.   0.   0.  29.  22.  17.   0. 118. 111.
   87.   0.   0.   0.  55. 179.  27.   0.   0.   0.   0. 128.   0.  25.
   64.  22.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  33.  23.   0.   0.   0.  29.  26.  76.  21.   0. 108.   0.
   34.  69.   0.   0.  40.   0.  22.  18.  26.  73. 137. 463. 359. 548.
  249.   0.  38.  42.  69.   0.   0.  41.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  61. 405. 526.
  335.   0.   0.   0.   0.   0.  64.   0.   0.  49.   0.   0.  63. 104.
    0.   0.   0.   0.   0.   0.  24.   0.]
 [ 68.   0.   0.  40.   0. 195.  25.   0.   0.   0.   0.   0.  39.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0. 359. 258. 101.  53.  20.
    0.   0.  76.  30.  22.  25. 104.   5.]
 [ 32.   0.   0.  18.   0.   0.   0.   0.   0.   0.   0.   0.   0. 398.
  509. 175.   0. 160.  12.   0.   0.   0.   0.   0.   0.   0.   0. 291.
  575. 183. 574. 564.  89.   0.   0.  31.]
 [  0.  32.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  19.   0.   0.  48.   0.   0.  37. 123. 108. 161.   0.  28.
    0.   0.  22.   0.   0.   0.  36.   0.]
 [ 81.  78. 303. 564. 349.   0.  78. 522. 713. 695. 660. 567. 567. 629.
  666. 614. 522. 544. 118. 175.  70. 160. 479.  47.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 120.   0.]
 [583. 630. 719. 479. 230.   0.  72.   0.  49.   0.   0.  37. 114.  87.
  169.   0. 218.  59.  58.  46. 178. 697. 625. 565.  33.  71. 104. 241.
   20. 140.  76.  66.   0.  28.  24. 111.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.  89.  40.   0.  22.   0.   0. 108.  73.   0.  25.   0.
    0.   0.   0.   0.   0.   0.  18.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [ 44. 107. 471. 770. 871. 866. 875. 874. 882. 886. 885. 536.   0. 597.
  883. 887. 889. 879. 892. 901. 552.   0. 129. 151.  66.   0.  21.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  40.   0.   0.   0.   0.   0.   0.   0.   0.   0.  66.   0. 137.
   72.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  77. 228.   0.
    0.   0.   0.   0.   0.   0.   0. 190.]
 [  0.   0.  67.  52.   0.  44.  48.   0.   0.   0.   0.   0.   0.   0.
    0.  67.  59.   0.   0.   0.   0.   0.   0.   0.   0.   0.  46.  16.
   72. 121.  62.   0.  76.  24.  19.  89.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.]
 [235.   0.  43.   0.   0.   0.   0.   0.   0.  20.   0.   0.   0.   0.
    0.   0.  84.  19. 452. 309.  35.   0.   0.   0.   0.  44.   0.   0.
    0.   0.   0.   0.   0.   0.   0.  88.]
 [  0.   0. 112.   0.  58. 119.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.  19. 205.  28.   0.  63.  44.  93.  42.  57.  26.   0.   0.
   48.  58.   0.   0.   0.   0.   0.   0.]]
Error for eta 350.0: 4332.6204740750245

In [27]:
best_eta

440